.gitignore, Dockerfile, Procfile, README.md, bin/clean_dist.sh, bin/config.sh.sample, bin/deploy.sh, bin/prod_deploy.sh
Une fois qu'on a ajouté un fichier `bin/config.sh` (non suivi par Git) et qu'on l'a rempli en s'inspirant de `bin/config.sample`, il est possible de déployer le logiciel sur une machine et un répertoire cible.
L'instance de production tourne dans un conteneur docker, qui écoute sur le port `3000`. La machine hôte de production écoute les requêtes sur le port spécifié (par défaut : `80`) et transmets les requêtes au conteneur.
=> Ajoute scripts de déploiement

LICENSE, README.md, package.json, src/public/index.html
Cette PR résout l'issue #12 en déclarant la licence AGPL-3.0 conformément à la décision de la réunion du mercredi 19 décembre
=> Déclare la licence AGPL-3.0

.circleci/config.yml
Cette PR est nécessaire pour la mise en place d'une intégration continue avec CircleCI
Elle contient le fichier de configuration de circleCI ne lançant pas les tests pour pouvoir simplement mettre en place l'outil.
=> Mise en place de CircleCI

package.json
Actuellement `webpack-dev-server` écoute, par défaut, sur 127.0.0.1. Pour pouvoir faire tourner le projet dans docker, j'ai besoin de lui faire écouter sur toutes les interfaces possible (pour pouvoir me connecter de l'extérieur.
=> Fait écouter le serveur webpack sur toutes les interfaces.

src/app/situationInventaire.js, src/situations/commun/vues/go.js, src/situations/commun/vues/stop.js, src/situations/inventaire/modeles/journal.js, src/situations/inventaire/vues/formulaireSaisieInventaire.js, tests/situations/commun/vues/go.js, tests/situations/commun/vues/stop.js, tests/situations/inventaire/modeles/journal.js, tests/situations/inventaire/vues/formulaireSaisieInventaire.js
J'ai rajouté l'enregistrement de l'appui sur les boutons go, stop et saisie d'inventaire. Lors de la validation de celui ci, le résultat ainsi que les valeurs rentrées sont aussi sauvegardé. 
Pour tester manuellement ce que j'ai fait, j'ai utilisé la page de restitution disponible localement: http://localhost:7700/restitution.html
Il manque un point de #43. Je compte m'en occuper après.
=> Enregistrement de plus d’événements dans l'inventaire

package-lock.json, package.json, src/app/restitutionSituationInventaire.js, src/app/situationInventaire.js, src/situations/inventaire/infra/depot_journal.js, src/situations/inventaire/modeles/journal.js, tests/situations/inventaire/infra/depot_journal.js, tests/situations/inventaire/modeles/journal.js
Le `session_id` était simplement une fausse chaine lors de l'envoi des événements au serveur. J'ai changé cela en utilisant un uuid généré au chargement de la page. Le journal le passe simplement a chaque enregistrement d'un événement. 
Pour tester, j'ai joué la situation inventaire, et j'ai vérifié sur la page restitution.html que j'avais un uuid qui était le même qu'auparavant.
=> Ajout d'un identifiant de session dans les événements.

src/situations/inventaire/vues/contenu.js, tests/situations/inventaire/vues/contenu.js
J'ai ajouté l'attente de l'événement "load" sur l'image du contenant ouvert avant d'afficher la vue contenu.
=> [CORRECTION] Corrige le glitch au moment de l'ouverture du contenant

src/situations/inventaire/infra/depot_journal.js, src/situations/inventaire/modeles/journal.js, tests/situations/inventaire/infra/depot_journal.js, tests/situations/inventaire/modeles/journal.js
Le json envoyé au serveur a changé un peu. `type_evenement` a été renommé en `nom` et `description` en `donnees`.
Avec cela, le serveur accepte de sauvegarder l'événement.
=> Met à jour les noms de paramètres envoyés au serveur.

src/app/situationControle.js, src/situations/controle/modeles/bac.js, src/situations/controle/modeles/piece.js, src/situations/controle/styles/bac.scss, src/situations/controle/vues/bac.js, src/situations/controle/vues/situation.js, tests/situations/controle/modeles/bac.js, tests/situations/controle/vues/bac.js, tests/situations/controle/vues/situation.js
Contribue à #54 
Ce code introduit le modèle `Bac` et la vue `VueBac`. J'ai l'intuition qu'on pourra réutiliser le code de ce modèle et de cette vue pour la situation « Tri ». C'est avec cette intention que j'ai fait certains choix de design (comme celui d'associer une « catégorie de pièce » à chaque bac).
=> Affiche bacs

src/situations/commun/infra/depot_journal.js, tests/situations/inventaire/infra/depot_journal.js
Grâce à betagouv/competences-pro-serveur#14, le serveur accepte désormais qu'on lui envoie le paramètre `donnees` en JSON. Nous avons pu enlever le `JSON.stringify` pour ne rien faire de spécial.
=> Envoie les données en JSON.

src/app/situationControle.js, src/app/situationInventaire.js, src/situations/commun/styles/cadre.scss, src/situations/commun/styles/commun.scss, src/situations/commun/vues/cadre.js, src/situations/inventaire/styles/etageres.scss, src/situations/inventaire/vues/situation.js, tests/situations/commun/vues/cadre.js
Cette PR prépare #79 :
- en insérant dans le navigateur un « cadre de situation », qui se charge d'afficher une situation qui lui est injectée
- en homogénéisant la structure `VueCadre` --> `VueSituation` entre les situations « Contrôle » et « Inventaire »
=> Introduis un composant « cadre de situation »

src/locales/fr.json
Pour uniformiser avec le nom de la situation inventaire. J'ai fait le choix de ne pas mettre dans le nom de la situation l'action qui doit être fait. Mais cela pourrait être changé en "Inventaire de boissons" et *Contrôle de biscuits* par exemple.
Ferme / fix #93
=> Met à jour le titre de la situation controle.

src/situations/inventaire/styles/etageres.scss, src/situations/inventaire/vues/contenants.js, src/situations/inventaire/vues/contenu.js, src/situations/inventaire/vues/etageres.js, tests/situations/inventaire/vues/etageres.js
Cette PR corrige un problème de redimensionnement des contenant ouvert qui vient d'être introduit avec la dernière correction sur la ré-intégration des barres des étagères dans les images de fond.
Cette PR corrige aussi le problème du dimensionnement du SVG sur safari (https://benfrain.com/attempting-to-fix-responsive-svgs-in-desktop-safari/)
=> [CORRECTION] Corrige le problème de dimension des contenants ouverts

src/app/situationInventaire.js, src/situations/commun/vues/consigne.js, src/situations/commun/vues/go.js, tests/situations/commun/vues/consigne.js, tests/situations/commun/vues/go.js
Cette PR contribue à l'issue #98 
- Refactoring de la vue Go pour passer le point d'insertion à la méthode affiche()
- Refactoring de la vue Consigne pour passer le point d'insertion à la méthode affiche() après avoir créer cette méthode.
=> passage du point d'insertion à `VueGo.affiche(…)` et `VueConsigne.affiche(…)`

src/app/situationControle.js, src/app/situationInventaire.js, src/situations/commun/styles/cadre.scss, src/situations/commun/vues/cadre.js, src/situations/inventaire/styles/app.scss, tests/situations/commun/vues/cadre.js
Cette PR participe à l'issue #98 
La vue cadre à la responsabilité de créer l'élément `<scene>` (pour accueillir la
vue situation) et la barre d'action.
Ces deux éléments doivent se partage l'espace verticale de l'écran et c'est la
responsabilité de cette classe VueCadre de porter ce partage de ressource.
Cela diminue aussi la duplication de la création de la barre d'action.
=> Donne à la vue cadre la responsabilité de créer la vue action

Dockerfile, config.json, src/situations/commun/infra/depot_journal.js, webpack.config.js
Le fichier de configuration pour le client qui stocke l'url du serveur n'est pas super pratique. En fonction de son environnement on doit le modifier en développement, et en production c'est la même galère. 
Je l'ai donc supprimé pour utiliser une variable d'environnement, `URL_SERVEUR` qui peut facilement être injecté comme on veut sans modifier des fichiers. 
La pr coté orchestrateur arrive juste après celle ci !
=> Supprime le fichier config.json

src/app/situationInventaire.js, src/locales/fr.json, src/situations/commun/styles/commun.scss, src/situations/commun/styles/go.scss, src/situations/commun/vues/go.js, tests/situations/commun/vues/go.js
Avance #78 en intégrant les consignes textuelles. Cette PR simplifie également la vue Go en utilisant jQuery.
=> consignes textuelles

src/situations/commun/vues/go.js, tests/situations/commun/vues/go.js
Corrige (et teste) un problème de style intervenu dans un précédent refactoring
=> applique le style bleu au bouton go

src/situations/commun/styles/cadre.scss, src/situations/commun/styles/commun.scss, src/situations/commun/styles/conteneur.scss
la conséquence est de remettre le lien vers le code en haut de page
=> corrige la hauteur de la scène sur les petits écrans

src/situations/commun/modeles/evenement.js, src/situations/commun/modeles/evenement_demarrage.js, src/situations/commun/modeles/evenement_stop.js, src/situations/commun/modeles/journal.js, src/situations/commun/vues/go.js, src/situations/commun/vues/stop.js, src/situations/inventaire/modeles/evenement_ouverture_contenant.js, src/situations/inventaire/modeles/evenement_ouverture_saisie_inventaire.js, src/situations/inventaire/modeles/evenement_saisie_inventaire.js, src/situations/inventaire/vues/contenants.js, src/situations/inventaire/vues/formulaireSaisieInventaire.js, src/situations/inventaire/vues/situation.js, tests/situations/commun/modeles/evenement.js, tests/situations/commun/modeles/evenement_demarrage.js, tests/situations/commun/modeles/evenement_stop.js, tests/situations/commun/modeles/journal.js, tests/situations/commun/vues/go.js, tests/situations/commun/vues/stop.js, tests/situations/inventaire/modeles/evenement_ouverture_contenant.js, tests/situations/inventaire/modeles/evenement_ouverture_saisie_inventaire.js, tests/situations/inventaire/modeles/evenement_saisie_inventaire.js, tests/situations/inventaire/vues/contenants.js, tests/situations/inventaire/vues/formulaireSaisieInventaire.js
Dans le chapitre précédent, un homme, enthousiaste, avait décidé d'enregistrer plus d'événements dans la situation inventaire. Il avait alors ajouté des méthodes du type `enregistreDemarrage` ou encore `enregistreOuvertureContenant` pour faire cela. Mais le journal avait une autre destinée. En effet, la situation contrôle a pointé le bout de son nez. Le journal a été déplacé. Les méthodes sont restées. 
Dans ce nouveau chapitre, pour permettre l'enregistrement d'événements dans n'importe quelle ~partie du royaume~ des situations , il a été décidé de déplacer les méthodes dans des classes événement. Une méthode générique `enregistreEvenement` s'occupe ainsi de récupérer son nom et les données associés.
=> Extrait les methodes du journal pour les remplacer par une méthode générique

src/locales/fr.json, src/situations/commun/styles/go.scss, src/situations/commun/vues/go.js, tests/situations/commun/vues/go.js
Cette PR contribue à l'issure #78
Elle prend en compte les messages tel que sur les images dans le répertoire de Thibault sur le drive.
J'ai renommé le nom de la variable et le style de `consigne-texte` vers `message` puis qu'il ne s'agit pas uniquement du message pour le bouton "lecture consigne"
=> Met les nouveaux messages de la vue Go. Change la place des messages

Dockerfile, src/situations/commun/infra/internationalisation.js, webpack.config.js
Lorsque j'avais branché l'internationalisation j'avais utilisé `process.NODE_ENV` au lieu de `process.env.NODE_ENV`. En remarquant que en prod on avait le message dans la console de *i18next*, j'ai voulu corriger dans #102. Mais en fait ce n'était pas nécessaire.
=> Corrige l'utilisation de NODE_ENV

src/situations/commun/assets/lecture-en-cours.svg, src/situations/commun/styles/bouton.scss, src/situations/commun/styles/go.scss, src/situations/commun/styles/overlay.scss, src/situations/commun/vues/go.js, tests/situations/commun/vues/go.js
Fix #78 
Affiche le bouton de consigne en cours et introduit une machine à états pour supprimer la duplication dans `VueGo` et simplifier le HTML
Cette PR permet également de passer la lecture de la consigne en appuyant sur la touche S
=> 78 bouton consigne en cours

src/situations/commun/infra/depot_journal.js, src/situations/commun/modeles/journal.js, src/situations/commun/vues/stop.js, tests/situations/commun/vues/stop.js
L'événement stop n'est pas correctement envoyé coté serveur actuellement, car on revient à l'accueil  immédiatement. 
Du coup, j'ai retourné une promesse dans le retour du dépot journal, qui est renvoyé lors de l'enregistrement dans le journal, qui est utilisé pour finalement revenir a l'accueil.
J'ai pu vérifier ainsi que l'événement stop est bien correctement sauvegardé.
=> Retourne une promesse dans le journal

src/situations/commun/modeles/situation.js, src/situations/inventaire/vues/situation.js, tests/situations/commun/modeles/situation.js, tests/situations/commun/vues/go.js
Cela change la manière de s'enregistrer au modèle situation pour ne pas
à avoir a instancier un événement inutile.
=> Utilise la classe plutot que la methode nom d'un événement dans le modèle situation.

src/situations/controle/modeles/bac.js, src/situations/controle/vues/situation.js
La situation contrôle n'utilisait pas correctement les modèles de bac instanciés dans le constructeur. Nous avons corrigé cela.
De plus nous faisons apparaître la première pièce immédiatement au démarrage.
Un petit peu de code a été simplifié.
Ces 3 modifications vous sont vendues dans une seule PR, composée de 3 commits. Comme la vente liée est interdite, nous pouvons vous proposer les 3 choses dans 3 PRs. Mais c'est plus cher.
=> Controle: nettoyage de quelques comportements

src/app/situationControle.js, src/situations/controle/modeles/evenement_disparition_piece.js, src/situations/controle/vues/piece.js, src/situations/controle/vues/situation.js, tests/situations/controle/modeles/evenement_disparition_piece.js, tests/situations/controle/vues/piece.js, tests/situations/controle/vues/situation.js
Contribue à #105.
L'idée est de commencer par enregistrer un événement, pour pouvoir plus tard ensuite affiner l'information enregistrée.
_(Note : on peut remarquer que si on ne touche pas à la pièce, elle conserve ses coordonnées de départ jusqu'à sa disparition… Ce point sera corrigé dans une autre PR.)_
=> Situation « Contrôle » : génère et enregistre un événement à la disparition de chaque pièce

src/app/situationControle.js, src/app/situationInventaire.js, src/situations/commun/vues/cadre.js, tests/situations/commun/vues/cadre.js, tests/situations/controle/vues/situation.js, tests/situations/inventaire/vues/situation.js
Cette PR termine l'issue #98 
La vue cadre crée la structure suivante : 
```
<cadre>
<scene></scene>
<actions></actions>
<consigne></consigne>
<go></go>
</cadre>
```
=>  Donne à la vue cadre la responsabilité de créer l'élement racine

src/situations/controle/styles/app.scss, src/situations/controle/styles/tapis.scss, src/situations/controle/vues/situation.js, src/situations/controle/vues/tapis.js, tests/situations/controle/vues/tapis.js
J'ai sorti la gestion du tapis dans une classe a part. Le tapis est en mouvement que dans l'état `démarré`. Cela gère par avance la gestion de la fin de la situation.
Voici le résultat avec un overlay invisible pour mettre en exergue ce comportement:
=> Controle: Le tapis démarre une fois la situation démarré, et s'arrête une fois fini

src/situations/commun/vues/cadre.js, src/situations/commun/vues/terminer.js, tests/situations/commun/vues/cadre.js
Lorsque la situation a démarré, le fait de quitter la situation en voulant revenir en arrière ou en fermant l'onglet va afficher une fenêtre de confirmation à l'utilisateur·trice.
J'ai regardé, il n'y a pas moyen d'envoyer l'événement de fin a ce moment la au serveur.
Fix #66
=> Affiche une confirmation avant de quitter si la situation a démarré.

src/situations/controle/modeles/piece.js, src/situations/controle/modeles/situation.js, src/situations/controle/vues/piece.js, src/situations/controle/vues/situation.js, tests/situations/controle/modeles/piece.js, tests/situations/controle/modeles/situation.js, tests/situations/controle/vues/piece.js, tests/situations/controle/vues/situation.js
Cette PR ajoute la gestion de la fin de la situation contrôle, une fois toutes les pièces disparu.
Elle apporte en plus un refactoring pour déplacer la logique dans le modèle contrôle, plutôt que dans la vue.
Trêve de bavardage, voici le résultat:
Contribue à #54
=> Controle: détecte la fin

src/situations/controle/modeles/bac.js, src/situations/controle/modeles/piece.js, src/situations/controle/modeles/situation.js, src/situations/controle/styles/bac.scss, src/situations/controle/vues/bac.js, src/situations/controle/vues/situation.js, tests/situations/controle/modeles/bac.js, tests/situations/controle/modeles/piece.js, tests/situations/controle/modeles/situation.js, tests/situations/controle/vues/bac.js, tests/situations/controle/vues/situation.js
- La situation connaît désormais ses bacs.
- Les bacs peuvent avoir un effet survolé
- Les pièces émettent des événement lorsqu'ils sont {dé,}-sélectionné
- Les bacs ont une méthode `contient(piece)`
- La situation écoute les différents événements des pièces pour détecter le survol d'un bac et changer l'état des bacs en conséquence
La détection pour savoir si la pièce est au dessus d'un bac est plutôt basique pour le moment. Mais on pourra l'améliorer plus tard quand on connaîtra les dimensions d'une pièce.
=> Contrôle: Détection du survol d'un bac

src/situations/commun/styles/conteneur.scss
Cela prévient la sélection des choses dans les situations comme dans la capture d'écran suivante:
=> Désactive la sélection des choses par le navigateur.

src/situations/controle/styles/piece.scss, src/situations/controle/vues/piece.js, tests/situations/controle/vues/piece.js
Auparavant, en suivant le scénario décrit dans #196, il était possible de déplacer deux pièces simultanément.
Désormais, la pièce sélectionnée a un z-index plus grand qui lui permet d'éviter ce genre de problèmes.
De plus les pièces qui sont sélectionnée sont réordonnées dans le DOM (en dernier pour préserver l'ordre naturel.
Fix #196
=> [Contrôle] empêcher le déplacement de deux pièces simultanées

src/situations/controle/styles/piece.scss, src/situations/controle/vues/piece.js, tests/situations/controle/vues/piece.js
J'ai fait le pas simple d'ajouter une classe "desactiver" qui empêche toutes actions utilisateur lors de la disparition de la pièce.
=> ajoute une classe desactiver lors de la disparition d'une piece

src/situations/controle/modeles/situation.js, src/situations/controle/vues/piece.js, src/situations/controle/vues/situation.js, tests/situations/controle/modeles/situation.js, tests/situations/controle/vues/piece.js, tests/situations/controle/vues/situation.js
La gestion du déplacement des pièces qui était géré par la vue pièce est désormais géré au niveau de la vue situation. Cela a pour effet de corriger un bug une fois que la pièce a disparu alors qu'elle était en cours de déplacement. Fix #187.
De plus au moment de la disparition, si la pièce était au dessus d'un bac, l'état survolé était toujours actif sur le bac.
=> Controle: change la gestion du déplacement des pièces

src/situations/commun/modeles/situation.js, src/situations/commun/vues/actions.js, src/situations/commun/vues/cadre.js, src/situations/commun/vues/stop.js, tests/situations/commun/vues/cadre.js, tests/situations/commun/vues/stop.js
Lors de la confirmation du stop lorsque la situation a démarré, on avait une confirmation en plus du à #163. 
La raison était que l'état de la situation était toujours `démarré`. Désormais l'état passe à `stoppée`, qui permet de ne pas afficher la confirmation du navigateur.
Fix #186
=> Fix la confirmation pour quitter la page lors de l'appui sur stop

all-tests.js
Le module node `jsdom` est notoirement long à charger, encore plus quand on est à l'intérieur
d'un conteneur Docker, encore plus depuis Docker sous Mac. Cela entraîne un timeout au niveau du
`beforeEach` qui charge en premier ce module. La solution proposée consiste à « pré-charger »
le module avant l'exécution du premier test.
Point discutable : on pré-charge `jsdom` même dans le cas où on n'exécute qu'une partie des tests.
=> Charge `jsdom` avant l'exécution du premier test

package-lock.json, package.json
La mise à jour de `@babel/preset-env` résout 'Browserslist: caniuse-lite is outdated'
Par ailleurs, j'ai aussi mise à jour webpack avec les dernières évolutions mineurs
=> Met à jour la chaine de construction pour résoudre une alerte

src/situations/controle/vues/situation.js, tests/situations/controle/vues/situation.js
1. Sélectionner une pièce
2. Déplacer la souris en maintenant le clic au dehors de la zone de la situation
3. Relâcher le clic
4. Revenir dans la zone de situation
5. La pièce se déplace sans maintenir le clic
Fix #197
=> Contrôle: Déselectionne toutes les pièces si le clic gauche n'est pas maintenu.

package-lock.json, package.json
https://nvd.nist.gov/vuln/detail/CVE-2019-11358
=> Met à jour JQuery pour corriger l'alerte CVE-2019-11358

src/situations/commun/infra/depot_journal.js, src/situations/commun/modeles/journal.js, src/situations/commun/styles/modale.scss, src/situations/commun/styles/stop.scss, src/situations/commun/vues/modale.js, src/situations/commun/vues/stop.js, tests/situations/commun/infra/depot_journal.js, tests/situations/commun/modale.js, tests/situations/commun/vues/stop.js
Cette PR, améliore le comportement de la fenêtre de confirmation, dans le cas ou le serveur ne répond pas ou répond lentement.
- La modale ne disparait pas immédiatement.
- La modale affiche un curseur d'attente.
- Au bout de 1 secondes, on quitte la situation, même si le serveur n'a pas traité.
=> Peut stopper sans serveur

src/situations/commun/styles/couleurs.scss, src/situations/commun/styles/stop.scss
La variable $couleur-fond-bouton-rouge n'existait pas, mais on en
utilisait une autre pour le style du bouton stop.
=> Introduis la variable $couleur-fond-bouton-rouge.

tests/situations/commun/vues/stop.js
Je ne suis pas sur pourquoi il y a un avertissement alors que finally
est censé permettre ne pas avoir de then ni de catch. Bref, c'est corrigé.
=> Corrige un avertissement d'exception non attrapée dans les tests.

src/situations/commun/styles/action_overlay.scss, src/situations/commun/styles/actions.scss, src/situations/commun/styles/rejoue_consigne.scss, src/situations/commun/vues/actions.js, src/situations/commun/vues/modale.js, src/situations/commun/vues/rejoue_consigne.js, src/situations/commun/vues/stop.js, tests/situations/commun/modale.js, tests/situations/commun/vues/actions.js, tests/situations/commun/vues/rejoue_consigne.js
Contribue à l'issue #68 
Cette PR couvre la priorité qui avait été donné mercredi 24/04, à savoir permettre à l'utilisateur de pouvoir rejouer la consigne.
Plusieurs autres points ont été invoqués ce même jour:
- Journaliser l'événement
- Mettre un player
- Rejouer la consigne accessible avant de cliquer sur GO
- La lecture de la consigne et la relecture de la consigne sont très proche, il faudrait refactorer ça pour éviter la duplication.
- La consigne est inaudible sur la situation Contrôle
Par simplicité et pour éviter un trop gros pas, j'ai pris le parti de simplement rejouer la consigne.
Si c'est OK pour vous on pourrait gérer les autres éléments dans des issues à part.
=> Permet à l'utilisateur de rejouer la consigne

package.json, webpack.config.js
Il y a un bug dans la version actuelle de webpack-dev-server qui casse le rechargement automatique de la page.
Le contournement officiel est de rajouter `disableHostCheck` dans la config. Voir https://github.com/webpack/webpack-dev-server/issues/1604
=> Désactive la vérification de l'hote pour la connexion websocket.

src/situations/commun/vues/consigne.js, src/situations/commun/vues/rejoue_consigne.js, tests/situations/commun/vues/consigne.js
Le comportement à adopter en cas d'impossibilité de la lecture de la
consigne n'est pas déterminé mais en tout cas, passer dans l'état
suivant n'est probablement pas ce que l'on veut.
=> [NETTOYAGE] supprime le traitement en cas d'erreur de lecture de la consigne

.gitignore
Ce répertoire était un vestigue de l'ancien méthode de déploiement.
=> [NETTOYAGE] supprime le répertoire `dist` du .gitignore

src/locales/fr.json, src/situations/accueil/vues/formulaire_identification.js, tests/situations/accueil/vues/formulaire_identification.js
Plutôt que d'avoir un bouton *OK* qui n'est pas clair, on enregistre la valeur du champ automatiquement.
=> Enregistre automatiquement la valeur du champ d'identification.

src/locales/fr.json, src/situations/controle/modeles/situation.js, src/situations/controle/styles/fin.scss, src/situations/controle/vues/fin.js, src/situations/controle/vues/situation.js, tests/situations/controle/modeles/situation.js, tests/situations/controle/vues/fin.js
A la fin de la situation contrôle, le nombre de pièces réussis, en erreurs et non triées sont affiché comme sur la maquette.
C'est le modèle qui maintient et stocke les chiffres.
Fix #170
=> Controle: affichage du résultat à la fin

src/situations/commun/vues/cadre.js, tests/situations/commun/vues/cadre.js
Pour éviter les fausses manipulations des utilisateurs pas très au taquet sur l'informatique.
Fix #271
=> Désactive le clic droit sur le cadre.

src/situations/commun/modeles/piece.js, src/situations/commun/vues/piece.js, src/situations/controle/data/pieces.js, src/situations/controle/infra/depot_ressources_controle.js, src/situations/controle/modeles/situation.js, src/situations/controle/vues/piece.js, src/situations/controle/vues/situation.js, src/situations/tri/data/pieces.js, src/situations/tri/infra/depot_ressources_tri.js, src/situations/tri/vues/situation.js, tests/situations/commun/vues/piece.js, tests/situations/controle/infra/depot_ressources_controle.js, tests/situations/controle/vues/piece.js, tests/situations/tri/infra/depot_ressources_tri.js, tests/situations/tri/vues/situation.js
Pour éviter d'avoir des `require` des fichiers images dans les données des situations contrôle et tri, elles contiennent désormais la référence de la pièce. La vue pièce va demander ensuite au dépot ressources le fichier image qui va bien.
Cela a également pour effet de précharger les bonbons dans la situation tri.
Cette PR est dépendante de #275, je vous invite a la lire avant.
Contribue à #213.
=> Les pièces du tri et contrôle utilisent le dépôt ressources

src/situations/commun/vues/piece.js, src/situations/controle/vues/piece.js, tests/situations/commun/vues/piece.js, tests/situations/controle/vues/piece.js
Le comportement de sélection d'une pièce est déplacée de la `VuePiece` du contrôle vers la `VuePiece` commune. 
Le tri en hérite par conséquent : on peut cliquer sur une pièce et constater qu'elle prend le focus. Ça lui redonne un côté flottant mais j'ai fait le choix de tolérer ça pour le moment.
Contribue à #213
=> déplace la sélection de la pièce dans la VuePiece commune

src/situations/controle/modeles/bac.js, src/situations/controle/modeles/situation.js, tests/situations/controle/modeles/bac.js
Maintenant que nous connaissons les dimensions de la pièce, il est plus
facile de savoir si une pièce est dans un bac ou non.
=> Améliore la méthode contient() du bac.

src/situations/commun/infra/depot_ressources.js, src/situations/commun/vues/actions.js, src/situations/commun/vues/consigne.js, src/situations/commun/vues/rejoue_consigne.js, tests/situations/commun/aides/mock_audio_node.js, tests/situations/commun/aides/mock_chargeurs.js, tests/situations/commun/infra/depot_ressources.js, tests/situations/commun/infra/depot_ressources_communes.js, tests/situations/commun/vues/consigne.js, tests/situations/commun/vues/rejoue_consigne.js, tests/situations/inventaire/infra/depot_ressources_inventaire.js
En effet, il semble que le chargement des ressources audio n'émette pas forcément
l'événement 'canplaythrough' sur Safari.
fix #270
=> Charge les resources audio en ajax et converti en audio avec webaudio

src/situations/commun/modeles/piece.js, tests/situations/commun/modeles/piece.js
Lorsque nous déplaçons les pièces, nous nous assurons de désélectionner toute les pièces dans certains cas, ce qui arrive ici: https://github.com/betagouv/competences-pro/blob/d4d9c0b2220cdd03573ff1ea384260134bb1785c/src/situations/commun/composants/deplaceur_pieces.js#L30
Ce qui a pour effet d'appeler les callbacks, comme celui de la vue pièce qui s'assure que la dernière pièce sélectionnée est toujours en dernier dans le dom pour avoir un ordre naturel https://github.com/betagouv/competences-pro/blob/d4d9c0b2220cdd03573ff1ea384260134bb1785c/src/situations/commun/vues/piece.js#L63
Mais comme le callback était appelé même lorsque la pièce n'était pas sélectionnée, on réordonnait toute les pièces en permanence ce qui cassait l'ordre d'affichage voulu.
=> N'émet aucun événements si la sélection d'une pièce n'a pas changé.

src/situations/commun/modeles/piece.js, src/situations/commun/vues/piece.js, src/situations/controle/modeles/situation.js, src/situations/controle/vues/piece.js, src/situations/tri/modeles/piece.js, src/situations/tri/modeles/situation.js, tests/situations/commun/vues/piece.js, tests/situations/controle/modeles/situation.js, tests/situations/controle/vues/piece.js, tests/situations/tri/modeles/piece.js, tests/situations/tri/modeles/situation.js
J'ai rajouté la logique de disparition et de réinitialisation des pièces dans le modèle.
Le code de la vue pour la disparition a été mis en commun entre le contrôle et le tri.
=> Tri: fait disparaitre les pièces bien placées et réinitialise celles mal placées

src/situations/commun/vues/affiche_situation.js, src/situations/commun/vues/cadre.js, src/situations/controle/infra/depot_ressources_controle.js, src/situations/controle/modeles/situation.js, src/situations/controle/vues/fond_sonore.js, src/situations/controle/vues/situation.js, tests/situations/commun/vues/actions.js, tests/situations/commun/vues/cadre.js, tests/situations/controle/aides/mock_depot_ressources_controle.js, tests/situations/controle/vues/fond_sonore.js, tests/situations/controle/vues/situation.js
Ceci nécessite la création de la vueSituation seulement après le chargement des
ressources
Grace à cette PR on passe à un `AudioNode` généré par `webAudio` qui gère mieux que `Audio` le bouclage d'un échantillon sonore (loop)
=> Contrôle : demande le fond sonore au dépôt ressources

src/situations/tri/styles/chronometre.scss
Pour Safari, il est indispensable que les deux propriétés `transform` (celle
de départ et celle de l'animation) contiennent les mêmes transformations.
Cette PR recentre aussi les aiguilles qui était quelques fraction de `rem` trop basses
fix #313
=> [CORRECTION] Fait tourner les aiguilles de la situation tri sur safari

src/situations/commun/styles/actions.scss, src/situations/commun/styles/bouton.scss, src/situations/commun/styles/cadre.scss, src/situations/commun/styles/dimensions.scss, src/situations/commun/styles/modale.scss, src/situations/commun/styles/overlay.scss, src/situations/commun/styles/terminer.scss, src/situations/commun/vues/action_overlay.js, src/situations/commun/vues/actions.js, src/situations/commun/vues/rejoue_consigne.js, src/situations/commun/vues/stop.js, tests/situations/commun/vues/actions.js, tests/situations/commun/vues/rejoue_consigne.js
~~Si on clique sur le bouton relectureConsigne avant que la situation a démarré il faudrait disable le bouton Go tant que la relecture de la consigne n'est pas terminé~~
=> Permettre à l'utilisateur de relire la consigne avant de cliquer sur GO

src/situations/tri/modeles/situation.js, tests/situations/tri/modeles/situation.js
A la dépose d'un bonbon, si il n'est pas dans un bac, celui ci n'est pas compté comme erreur et on ne réinitialise pas la position.
En cas d'erreur, la solution choisie est de remettre le bonbon dans sa position originelle. Potentiellement on pourrait le remettre dans sa dernière position.
=> Tri: Ne réinitialise pas le bonbon si il n'est pas dans un bac.

src/situations/inventaire/vues/contenu.js, tests/situations/inventaire/vues/contenu.js
fix #321 
Sur Safari, l'événement `load` n'est pas envoyé si l'image n'est pas modifié
(ré-affectation d'une nouvelle valeur à l'attribut `src`). Ceci avait pour conséquence de ne pas pouvoir ouvrir deux fois de suite le même contenant.
Comme nous n'avons plus besoin d'attendre la fin du chargement de l'image
depuis que nous avons mis en place le préchargement, la solution a simplement
consisté à supprimer l'attente de l'événement `load` dans la vue contenu.
=> [CORRECTION] Inventaire : supprime l'attente sur l'événement load pour l'ouverture contenant

src/situations/inventaire/vues/formulaire_saisie_inventaire.js
Cela va éviter que des personnes mettent plein de caractères dans les
champs de saisie.
=> Inventaire: Limiter la taille des champs de saisie à 2 caractères.

src/situations/controle/modeles/situation.js, tests/situations/controle/modeles/situation.js
fix #336 sauf que pour simplifier j'attends un cycle du cadencement qui est de 5 secondes et non 4.
Je propose cette solution pour l'instant en attendant que nous implémentions peut-être un jour la sequence variable d'affichage des biscuits.
=> [Contrôle] Attendre 5 secondes avant d'afficher le premier biscuit

src/situations/inventaire/styles/formulaire_saisie_inventaire.scss, src/situations/inventaire/vues/formulaire_saisie_inventaire.js
Contribue à #315 (… mais le problème est beaucoup plus large !)
En l'état, le fait d'enlever le `@import` de `font_awesome.scss` de `formulaire_saisie_inventaire.scss` supprime une des duplications d'import. Et ce n'est déjà pas si mal 😉
=> Déplace l'import SCSS à l'endroit approprié

src/situations/commun/styles/commun.scss
=> [Accueil] intègre la nouvelle police qui remplace Helvetica Neue

src/situations/accueil/styles/accueil.scss
Avec une petite résolution en hauteur, l'image de fond de l'accueil rétrécissait.
=> Corrige le fond de l'accueil pour ne pas se déformer en redimensionnant.

src/situations/accueil/vues/accueil.js, src/situations/commun/infra/registre_utilisateur.js, tests/situations/accueil/vues/accueil.js, tests/situations/commun/infra/registre_utilisateur.js
Si je suis connecté en tant que `Roger`, que j'effectue l'exercice d'une première situation, et que je reviens à la page d'accueil, la progression pointe vers la 2e situation (jusqu'ici, tout va bien).
Si je me déconnecte et que je me reconnecte en tant que `Gérard`, la progression doit pointer vers la 1ère situation. Et seule la première situation doit être accessible.
=> [CORRECTION] Remets la progression au début quand déconnexion utilisateur

src/situations/commun/composants/joueur_consigne.js, src/situations/commun/infra/depot_ressources.js, src/situations/commun/vues/consigne.js, src/situations/commun/vues/rejoue_consigne.js, tests/situations/commun/vues/rejoue_consigne.js
Fix #358 
Nous avons rencontré les problèmes suivants avec Safari :
- Le jeu de deux sons en même temps ne marche pas dans le contrôle (le fond sonore plus les klaxons)
- l'événement "ended" n'est pas toujours émis
- parfois la méthode `start` est bien appelée mais aucun son n'est joué (par exemple la deuxième partie de la consigne n'est pas jouée).
Pour corriger tous ces problèmes, cette PR supprime l'usage de webkitAudioContext. Si `window.AudioContext` n'est pas disponible, on bascule sur l'utilisation de `window.Audio`.
Conséquence pour Safari :
Les sons sont joués de manière un peu moins jolie (en particulier le son du tapis du contrôle qui est joué en boucle subit une petite coupure).
=> Supprime webkitAudioContext et factorise le code pour jouer la consigne

src/situations/accueil/styles/acces_situation.scss, src/situations/accueil/vues/acces_situation.js, src/situations/accueil/vues/accueil.js, tests/situations/accueil/vues/acces_situation.js, tests/situations/accueil/vues/accueil.js
Avant, la logique de désactivation de situation était réparti entre la vue `Accueil` et la vue `AccesSituation`.
Désormais, `AccesSituation` sait se mettre à jour lorsque cela change.
=> Accueil: déplace la logique de désactivation des situations dans la vue AccesSituation

src/situations/tri/vues/situation.js
Certaines pièces sont placés juste devant les bacs, ce qui empéchait
leur sélection sur la partie qui recouvrait le bac.
=> Tri: Permet de sélectionner les pièces qui sont juste devant un bac.

tests/situations/accueil/modeles/acces_situation.js
C'est le cas aujourd'hui de la situation compte-rendu et j'avais peur que ça plante.
=> Ajoute un test pour vérifier qu'une situation est bien inaccessible si le niveau n'est pas précisé.

src/situations/commun/infra/registre_utilisateur.js, src/situations/commun/modeles/journal.js, src/situations/commun/vues/boite_utilisateur.js, tests/situations/accueil/vues/accueil.js, tests/situations/accueil/vues/formulaire_identification.js, tests/situations/commun/infra/registre_utilisateur.js, tests/situations/commun/modeles/journal.js, tests/situations/commun/vues/boite_utilisateur.js
Avec betagouv/competences-pro-serveur#92 qui rajoute le modèle d'évaluation, désormais à l'identification, on fait un appel au serveur pour en créer une. On sauvegarde son identifiant pour le passer aux événements a la place du nom de l'utilisateur.
Cela ne change pas le workflow actuel, mais il faudra penser a améliorer l'UX du formulaire d'identification pour gérer un spinner et la désactivation du bouton lorsqu'une requête est faite (ainsi que gérer les erreurs).
=> Récupère et utilise l'id de l'évaluation

src/locales/fr.json
Pour éviter une répétition qui répète le mot carton.
=> Questions: corrige la description de numératie

src/locales/fr.json, src/situations/accueil/styles/formulaire_identification.scss, src/situations/accueil/vues/formulaire_identification.js, src/situations/commun/infra/registre_utilisateur.js, tests/situations/accueil/vues/formulaire_identification.js
contribue #383 
Permet à l'utilisateur de saisir le code de la campagne à laquelle il participe, cela permettra de relier l'évaluation à cette campagne, et par la suite de récupérer la configuration de cette campagne.
En l'état, si l'utilisateur se trompe de code cela ne provoque pas d'erreur et l'affectera à la première campagne de la liste. C'est un comportement que j'espère changer dans une PR à part.
=> Permet de saisir le code de campagne à l'identification

src/situations/commun/composants/joueur_consigne.js, src/situations/commun/infra/depot_ressources.js, src/situations/commun/vues/actions.js, src/situations/commun/vues/consigne.js, src/situations/commun/vues/rejoue_consigne.js, tests/situations/commun/aides/mock_audio_node.js, tests/situations/commun/composants/joueur_consigne.js, tests/situations/commun/vues/consigne.js, tests/situations/commun/vues/rejoue_consigne.js
Fix #411 
- On est repassé sur webkitWebAudio pour Safari.
- L'évenement "ended" n'est pas géré correctement par safari. A la place on synchronise la lecture des sons avec un timer javascript.
- La lecture de plusieurs sons en même temps (pour le contrôle) a été résolu par l'instanciation d'une instance unique pour WebAudioContext.
=> Fix lecture des sons ios

src/situations/commun/vues/action_overlay.js, src/situations/commun/vues/consigne.js, src/situations/commun/vues/go.js, src/situations/commun/vues/joue.js, tests/situations/commun/vues/action_overlay.js
Pour éviter le genre de comportement ci-dessous je n'ai pas limité l'overlay de chargement à la hauteur de la `scene`, ainsi il prend tout le `conteneur`.
Avant
Aprés
=> cache l'affichage de la situation tant que cette dernière n'a pas fini son chargement 

src/situations/questions/vues/qcm.js, tests/situations/questions/vues/qcm.js
Cela corrige les problèmes de double click et d'événements avec une réponse vide qui casse la restitution.
=> [Bureau] Désactive le bouton réponse lorsque aucune réponse est sélectionné et une fois répondu 

tests/situations/commun/vues/cadre.js
- Corrige le test pour qu'il ne plante plus silencieusement
- Corrige un autre test qui aurai pu planter silencieusement aussi
- Ré-initialise les événements attachés à `windows` avant chaque test
=> Corrige un test de la vue cadre qui plantait silencieusement

src/situations/commun/vues/modale.js, tests/situations/commun/modale.js
Quand l'action OK consiste à naviger vers l'accueil, la fenêtre disparait trop
tôt et ça fait un effet "glitch".
Comme nous n'avons aujourd'hui pas d'autre usage que de naviguer vers
l'accueil, j'ai supprimé la disparition de la fenêtre dans le cas de l'action
OK.
=> La fenêtre modale ne disparait plus après l'action OK

src/situations/accueil/styles/formulaire_identification.scss
Il faut donner une largeur à la case à cocher quand on l'utilise dans un `flex`.
=> [Safari] corrige l'affichage de la checkbox sur le formulaire d'identification

src/situations/accueil/modeles/store.js, src/situations/commun/infra/registre_utilisateur.js, tests/situations/accueil/modeles/store.js, tests/situations/commun/infra/registre_utilisateur.js
De manière à s'assurer que la progression qui se trouve dans le localstorage est
bien vide au moment de commencer.
Fix #465
=> Initialise la progression de l'évalué au moment de la connexion

src/situations/accueil/styles/accueil.scss, src/situations/commun/styles/boite_utilisateur.scss, src/situations/commun/vues/boite_utilisateur.vue, tests/situations/commun/vues/boite_utilisateur.js
=> Revoit l'affichage du nom de l'évalué·e.

src/situations/commun/composants/deplaceur_pieces.js, src/situations/commun/modeles/piece.js, src/situations/commun/vues/piece.js, src/situations/controle/vues/piece.js, src/situations/controle/vues/situation.js, src/situations/tri/vues/situation.js, tests/situations/commun/composants/deplaceur_pieces.js, tests/situations/commun/modeles/piece.js, tests/situations/commun/vues/piece.js, tests/situations/controle/vues/piece.js
fix #206 
Ajoute la gestion des événements tactils pour que l'on puisse jouer sur tablette.
Il reste malgré tout d'autres adaptations à faire. 
- Les consignes audios parlent de cliquer
- à valider que l'écran s'affiche correctement en mode paysage.
Cette PR ne prend pas en charge le multi-touch. Il n'est possible de déplacer qu'une seule pièce à la fois.
=> gestion événements tactiles

src/situations/securite/styles/situation.scss, src/situations/securite/vues/situation.vue, tests/situations/securite/vues/situation.js
Une fois qualifiées, les zones de danger restent "active".  J'ai gardé le même style que la sélection en attendant que le design s'affine.
=> Sécurité: Met en évidence les zones de dangers déjà trouvées.

src/situations/inventaire/styles/contenu.scss
=> Supprime le `tap-highlight` de l'inventaire à la fermeture d'un contenant

src/situations/securite/vues/fenetre_zone.vue, src/situations/securite/vues/formulaire_radio.vue, src/situations/securite/vues/situation.vue, tests/situations/securite/vues/fenetre_zone.js, tests/situations/securite/vues/situation.js
Cela permet de recliquer sur une zone juste après l'avoir qualifié. Actuellement c'est impossible.
=> Sécurité: Déselectionne la zone une fois l'identification ou la qualification terminée

.gitignore, package-lock.json, package.json, src/situations/accueil/vues/acces_situation.vue, src/situations/accueil/vues/accueil.vue, src/situations/accueil/vues/fin.vue, src/situations/accueil/vues/formulaire_identification.vue, src/situations/accueil/vues/overlay_intro.vue, src/situations/commun/vues/boite_utilisateur.vue, src/situations/securite/vues/fenetre_zone.vue, src/situations/securite/vues/formulaire_radio.vue, src/situations/securite/vues/situation.vue
Pour rajouter le support des fichiers vue, on ne peut pas passer par `semistandard` directement, il faut passer la config réutilisable eslint.
=> Configure eslint pour passer sur les fichiers vue

src/situations/securite/modeles/evenement_qualification_danger.js, src/situations/securite/modeles/rapporteur.js, src/situations/securite/vues/situation.js, tests/situations/securite/modeles/evenement_qualification_danger.js, tests/situations/securite/modeles/rapporteur.js
A chaque fois qu'un danger est qualifié, on envoi l'événement `qualificationDanger` avec le nom du danger et la réponse choisi.
=> Securité: envoi l'événement qualification danger

src/situations/securite/vues/situation.vue
Plutot que de créer une clef à partir des coordonnées des zones.
=> Utilise l'id de la zone pour la clef dans vue.

src/locales/fr.json, src/situations/commun/modeles/situation.js, src/situations/commun/vues/actions.js, src/situations/commun/vues/bouton.js, src/situations/commun/vues/cadre.js, src/situations/commun/vues/go.js, src/situations/commun/vues/rejoue_consigne.js, tests/situations/commun/modeles/situation.js, tests/situations/commun/vues/actions.js, tests/situations/commun/vues/cadre.js, tests/situations/commun/vues/go.js, tests/situations/commun/vues/rejoue_consigne.js
Lorsqu'une situation a un mode entraînement disponible:
- la vue go affiche un message: "Vous pouvez commencer l’entraînement"
- le bouton stop et rejoue consigne sont actif pendant entraînement
- une fois entraînement terminé, la vue go affiche un message: "Bravo vous avez terminé l'entraînement"
- pendant la situation, le bouton rejoue consigne est caché
A part cela, les autres situations devraient continué a fonctionner comme auparavant
Quelques screens dans une situation avec entrainement pour tester
=> Ajout d'un mode entrainement dans le cadre

src/situations/commun/styles/conteneur.scss
Fix #512 
Lorsque la fenetre n'est pas assez large, une barre de défilement verticale et horizontale est affiché. La barre verticale est présente car on mis un `min-height: 100vh` sur le body, et la scrollbar horizontal prend de la hauteur :/. C'est un moindre mal pour le moment.
=> Empêche le conteneur d'être redimmensionné en fonction de l'espace disponible

src/situations/securite/vues/situation.vue, tests/situations/securite/vues/situation.js
Une fois une zone ouverte, on ne peut plus clique sur la situation pour en ouvrir une autre. On est obligé d'identifier/qualifier avant.
=> Sécurité: Empêche l'ouverture de zone une fois l'une déjà ouverte.

src/situations/securite/styles/acte.scss
=> Sécurité: Change le style des zones de dangers qualifiés.

src/situations/questions/vues/qcm.js, tests/situations/questions/vues/qcm.js
Fix #538 
> The DOM input event is fired synchronously when the value of an <input>, <select>, or <textarea> element is changed. For input elements with type=checkbox or type=radio, the input event should fire when a user toggles the control (via touch, mouse or keyboard) per the HTML5 specification, but historically, this has not been the case. Check compatibility, or attach to the change event instead for elements of these types.
=> Bureau: Utilise l'événement change plutôt que input.

src/situations/inventaire/vues/contenu.js, src/situations/inventaire/vues/etageres.js, src/situations/inventaire/vues/situation.js, tests/situations/inventaire/vues/contenu.js, tests/situations/inventaire/vues/etageres.js
J'ai normalisé a la façon pré-vue la vue étagères pour avoir un constructeur avec la situation et une méthode `affiche` avec le point d'insertion.
La vue contenu elle a été refactoré pour qu'elle recrée l'élément image a chaque affichage. Cela permet d'éviter un clignotement lors du changement sous Firefox et permet un changement du contenu avec l'activation de l'aide #544
=> Inventaire: refactoring de la vue étagères et contenu

tests/situations/accueil/vues/accueil.js, tests/situations/accueil/vues/fin.js, tests/situations/accueil/vues/formulaire_identification.js, tests/situations/accueil/vues/index.js
J'ai rendu la variable local et donc il faut l'attacher à la vue locale à chaque fois qu'on en a besoins. 
Est-ce que c'est mieux ?
Ça me gênait que cette déclaration soit dans le fichier `tests/situations/accueil/vues/formulaire_identification.js`. Peut-être qu'on aurai pu la garder déclaré globalement mais alors à un endroit plus évident.
=> Tests : supprime l'initialisation global de Vue.prototype.$traduction

bin/test.sh
Commande pour avoir le "dot reporter"
`npm test -- -r dot`
Et combiné avec le mode watch
`npm test -- -r dot --watch`
Réporteur minimal
`npm test -- -r min --watch`
Réporteur avec une barre de progression
`npm test -- -r progress --watch`
=> Ajoute une option permetant de choisir le rapporteur de test

src/situations/accueil/styles/accueil.scss, src/situations/commun/assets/play.svg, src/situations/commun/assets/stop.svg, src/situations/commun/styles/barre_dev.scss, src/situations/commun/styles/boite_utilisateur.scss, src/situations/commun/styles/bouton.scss, src/situations/commun/styles/boutons.scss, src/situations/commun/styles/commun.scss, src/situations/commun/styles/couleurs.scss, src/situations/commun/styles/erreur_chargement.scss, src/situations/commun/styles/fin.scss, src/situations/commun/styles/mixins/boutons.scss, src/situations/commun/vues/bouton.js, src/situations/commun/vues/stop.js, src/situations/inventaire/styles/formulaire_saisie_inventaire.scss, src/situations/questions/styles/situation.scss, src/situations/securite/styles/acte.scss, src/situations/securite/styles/fenetre_aide.scss, tests/situations/commun/vues/bouton.js, tests/situations/commun/vues/stop.js
Des variables ont été supprimés et renommés et le style des boutons d'actions ont changé.
Quelques exemples:
=> Nouveaux style des boutons d'actions 

src/situations/accueil/styles/formulaire_identification.scss, src/situations/commun/styles/action_overlay.scss, src/situations/commun/styles/boite_utilisateur.scss, src/situations/commun/styles/boutons.scss, src/situations/commun/styles/commun.scss, src/situations/questions/styles/situation.scss, src/situations/questions/vues/qcm.js, src/situations/questions/vues/redaction_note.js
Après une discussion avec Benjamin, j'ai ajusté quelques élements de design à sa demande.
- Couleur du texte en "bleu-sombre" par défaut
- Ajout d'espace sur le formulaire de connexion
- Normalisation de la taille des boutons. Il n'y a que deux tailles différentes dans l'application. Une 3eme est possible mais utilisé seulement sur le site vitrine.
Exemple de rendu sur le formulaire de connexion
=> Ajustement d'éléments de design

src/situations/commun/styles/boite_utilisateur.scss, src/situations/commun/vues/boite_utilisateur.vue
=> Design: allonge la boite de progression de l'utilisateur

src/situations/accueil/modeles/store.js, src/situations/accueil/vues/accueil.vue, src/situations/accueil/vues/fin.vue, tests/situations/accueil/modeles/store.js, tests/situations/accueil/vues/accueil.js, tests/situations/accueil/vues/fin.js
Les deux actions `synchroniseSituations` et `recupereCompetencesFortes` ont été fusionnées car elles récupéraient la même URL, mais pas les mêmes infos dedans.
Et si le serveur nous renvoie une 404, on se déconnecte (cela permet de gérer la suppression d'évaluation coté serveur, alors que le client ne s'est pas déconnecté).
=> Refactore la récupération de l'évaluation

src/situations/commun/modeles/evenement_piece_prise.js, src/situations/controle/vues/situation.js, src/situations/tri/vues/situation.js, tests/situations/commun/modeles/evenement_piece_prise.js, tests/situations/controle/aides/mock_depot_ressources_controle.js, tests/situations/controle/vues/situation.js, tests/situations/tri/vues/situation.js
Lorsqu'une pièce (bonbon ou biscuit) est prise par un·e évalué·e, alors on enregistre un événement `piecePrise`.
Contribue à https://github.com/betagouv/competences-pro-serveur/issues/224 et https://github.com/betagouv/competences-pro-serveur/issues/225
=> Enregistre l'événement de prise de pièce dans le contrôle et le tri

src/situations/controle/vues/situation.js, tests/situations/controle/vues/situation.js
On ne peut pas différencier le type de biscuit coté serveur actuellement car on sait simplement si celui ci est conforme on non conforme. En rajoutant son type, nous saurons le faire.
Contribue à https://github.com/betagouv/competences-pro-serveur/issues/224
=> Ajout du type de pièce dans le controle.

src/situations/questions/modeles/situation.js, tests/situations/questions/modeles/situation.js
Le dernier événement de réponse est envoyé avant celui de fin de situation.
=> Corrige l'ordre des événement a la fin des questions.

.circleci/config.yml
La preprod sera disponible sur `preprod.eva.beta.gouv.fr` et `apipreprod.eva.beta.gouv.fr`.
Contribue à #617
=> Change les domaines de la preprod.

src/situations/commun/modeles/piece.js, src/situations/controle/modeles/evenement_piece_depose_dans_bac.js, src/situations/controle/modeles/situation.js, src/situations/controle/vues/situation.js, tests/situations/controle/modeles/evenement_piece_depose_dans_bac.js, tests/situations/controle/modeles/situation.js, tests/situations/controle/vues/situation.js
Contribue à #631
Lorsqu'un biscuit est déposé dans un bac, on enregistre désormais un événement `pieceDeposeDansBac` qui permettra de calculer le temps entre la prise de biscuit et la dépose.
=> Contrôle: enregistre un événement de dépose de pièces

src/locales/fr.json
=> ajoute des retours à la ligne pour le message d'abandon

src/locales/fr.json, src/situations/accueil/vues/fin.vue
=> affiche le nom de l'évalué-e sur l'écran de fin

src/situations/accueil/styles/fin.scss
pour fix #663 
J'ai choisi de le permettre dans toutes les modales, parce que ça m'embêtait de mettre une règle spécifique pour l'écran de fin et que j'ai l'impression que c'est pas un problème.
=> permet de copier-coller le texte dans les modales

src/situations/accueil/styles/fin.scss, src/situations/commun/styles/cadre.scss, src/situations/commun/styles/conteneur.scss
Il est essentiel d'interdire la sélection du texte dans les scènes de jeux. Pour les pièces du tri ou du contrôle par exemple.
Par contre, on veut autoriser la sélection du texte sur l'écran de fin.
Question : Est-ce que pour les campagnes mTurk, on veut absolument interdire la sélections du nom de l'utilisateur dans la div de progression ?
=> Desactive la selection du texte pour les scènes de jeux (mais pas pour le reste)

src/situations/commun/data/scene.js, src/situations/commun/modeles/store.js, src/situations/commun/styles/couleurs.scss, src/situations/commun/vues/adaptateur_situation.js, src/situations/commun/vues/situation.vue, src/situations/prevention/data/zones.js, src/situations/prevention/modeles/store.js, src/situations/prevention/styles/acte.scss, src/situations/prevention/vues/acte.vue, src/situations/prevention/vues/situation.js, src/situations/securite/data/zones.js, src/situations/securite/modeles/store.js, src/situations/securite/vues/acte.vue, src/situations/securite/vues/situation.js, src/situations/securite/vues/situation.vue, src/situations/tri/data/pieces.js, tests/situations/commun/modeles/store.js, tests/situations/commun/vues/situation.js, tests/situations/prevention/modeles/store.js, tests/situations/prevention/vues/acte.js, tests/situations/securite/modeles/store.js, tests/situations/securite/vues/situation.js
En plus d'afficher les zones dans la situation prévention, cette PR sépare le store de sécurité et de prévention ainsi que les vue Acte (mais garde une partie en commun).
Contribue à #669
=> Prévention: affiche les zones

src/situations/prevention/modeles/store.js, src/situations/prevention/styles/acte.scss, src/situations/prevention/vues/acte.vue, src/situations/prevention/vues/action_evaluation.vue, tests/situations/prevention/modeles/store.js, tests/situations/prevention/vues/acte.js
Au click sur un panneau, le résultat est désormais stocké dans le store. La zone est également affiché un peu différemment. 
Contribue à #669
=> Prévention: enregistre le click sur un panneau

src/situations/maintenance/vues/lexique.vue
Contribue à la #704 
Permet de commencer a utiliser les flèches directionnelles directement au démarrage de la situation.
=> Met le focus sur la situation Maintenance

src/situations/prevention/styles/acte.scss, src/situations/prevention/styles/action_prevention.scss, src/situations/prevention/vues/acte.vue, src/situations/prevention/vues/action_prevention.vue, tests/situations/prevention/vues/acte.js
Pour permettre la sélection d'une action a la fin du processus et l'animation inverse, j'ai réintroduit l'utilisation des transitions css, mais cette fois en les chainant.
Contribue à #669
=> Prévention: choix d'une action

tests/situations/accueil/infra/depot_ressources_accueil.js, tests/situations/commun/infra/depot_ressources_communes.js, webpack.config-test.js
Spécifiquement ce message
> WARNING in Conflict: Multiple assets emit different content to the same filename assets/consigne_demarrage.wav
Problème réglé dans la config webpack de prod en changeant le nom des
fichiers a la compilation.
=> Supprime des warnings dans les tests.

src/app/index.js, src/situations/commun/infra/report_erreurs.js, src/situations/commun/vues/adaptateur_situation.js
En cas d'erreur dans un composant vue, aucune erreur n'était remonté dans rollbar.
=> Configure vue pour envoyer les erreurs à rollbar.

src/situations/accueil/vues/fin.vue
Elle n'est plus utilisé depuis d7a52e94bca723b916beeb55571b2d1965418f54.
=> Supprime la méthode deconnecte qui n'est plus utilisé.

src/situations/accueil/vues/accueil.vue
Derrière l'écran d'identification et d'intro, on voit que le bouton suivant n'est pas correctement placé, ceci parce que le bouton pour rejoindre une situation n'est pas présent dans ce cas. 
En mettant une div vide, on pousse le bouton a la bonne place.
Avant:
Après:
=> Corrige l'affichage des flèches précédentes/suivante sur l'écran d'intro

src/situations/prevention/styles/acte.scss, src/situations/prevention/vues/acte.vue, tests/situations/prevention/vues/acte.js
https://www.loom.com/share/112969829ef944569c6753dd362b66aa
Fix #755 
Remarque : cette PR introduit un changement de paradigme sur la manière d'afficher les vignettes, on n'utilise plus le SVG. Il s'agit ici d'un premier pas, qui est proposé pour discussion et validation du principe. S'il est validé, il sera intéressant de propager ce principe sur les autres étapes de la vignette.
=> Corrige le bug de transition sur Chrome pour la situation Prévention

src/situations/accueil/infra/depot_ressources_accueil.js, src/situations/accueil/vues/acces_situation.vue, tests/situations/accueil/infra/depot_ressources_accueil.js, tests/situations/accueil/vues/acces_situation.js
Ce n'est pas normal d'avoir une situation sans bâtiment mais cette correction évitera d'avoir du bruit dans les erreurs rollbard tant que le bâtiment n'est pas là. Si le bâtiment n'est pas là, ça se voit.
fix #826
=> Ne fait pas d'erreur si on ajoute à l'accueil une situation sans bâtiment

src/situations/objets_trouves/infra/depot_ressources_objets_trouves.js, src/situations/objets_trouves/vues/situation.js, tests/situations/objets_trouves/aides/mock_depot_ressources_objets_trouves.js, tests/situations/objets_trouves/infra/depot_ressources_objets_trouves.js
De manière à ne pas dupliquer les noms des applications dans le dépôts
des ressources, j'ai préféré charger les ressources à partir des datas.
Ceci induit le risque qu'une ressource ne soit pas chargée puisqu'on ne
passe pas par dépôt ressources au moment où l'on cherche à l'afficher.
(La vue utilise directement la données qui se trouve dans data).
A noter que ce risque a déjà été pris pour les MES Question et Livraison,
bien que ce soit pour une raison différente.
fix #863
=> Objets trouvés : préchargement des ressources visuelles déclarées dans data

src/situations/objets_trouves/modeles/store.js, tests/situations/objets_trouves/modeles/store.js
Corrige l'erreur 
```
---> <Accueil> at src/situations/objets_trouves/vues/accueil.vue
<Root>
TypeError: Cannot read property 'length' of undefined
at Proxy.eval (webpack:///./src/situations/objets_trouves/modeles/store.js?:64:65)
at Proxy.render (webpack:///./src/situations/objets_trouves/vues/accueil.vue?./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options:109:49)
at VueComponent.Vue._render (/app/node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
at VueComponent.updateComponent (/app/node_modules/vue/dist/vue.runtime.common.dev.js:4054:21)
at Watcher.get (/app/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
at Watcher.run (/app/node_modules/vue/dist/vue.runtime.common.dev.js:4540:22)
at …
```
=> Corrige les warnings silencieux de la suite de test

src/situations/objets_trouves/data/apps.js
Pour correspondre au design présent sur figma, j'ai séparé la description et la question de l'application Agenda de l'entrainement pour objet trouvés.
=> Agenda Objets trouvés : Sépare la description de l'intitulé de la question

src/situations/commun/vues/qcm.vue, src/situations/questions/modeles/store.js, src/situations/questions/vues/acte.vue, tests/situations/questions/modeles/store.js, tests/situations/questions/vues/acte.js
Dans le cas des abandons on envoyait un événement d'ouverture de question après l'abandon, comme c'était le cas pour la fin.
De plus avec la correction pour le cas de la fin de situation, on avait perdu l'affichage de la dernière question derrière le message "bravo vous avez terminé".
J'ai révisé la façon de traiter la fin des questions et j'ai implémenté l'envoie de l'événement d'ouverture avec une propriété passé à la vue.
=> Corrige dernier événement questions

package-lock.json, package.json
- dépendance de dev : CVE-2020-7720 (node-forge >=0.10.0)
https://github.com/advisories/GHSA-92xj-mqp7-vmcj
- autre mise à jour de la commande `npm audit fix`
=> Mise à jour de sécurité diverses

src/locales/fr.json
Pour corriger le problème suivant :
=> Supprime un caractères non affichable qui s'était glissé dans une traduction

src/situations/questions/styles/redaction_note.scss, src/situations/questions/vues/redaction_note.vue
Pour répondre au ticket : https://trello.com/c/f1IPFcmu
Cette PR supprime quelques styles CSS. pour compléter la correction, il m'a aussi fallu supprimer l'expéditeur et refaire faire une image de fond. 
J'ai déjà chargé la nouvelle image en production. Je l'ai aussi mise dans le drive `<drive>/Assets_graphiques/4_Bureau/exports_backgrounds/20210215-bg-redaction_note.jpg`
=> Mise à jour du style de la note de rédaction

src/situations/maintenance/styles/lexique.scss, src/situations/maintenance/vues/touche.vue, tests/situations/maintenance/vues/touche.js
Ce bug fait suite au ticket : https://trello.com/c/rxM3Wdqb/584-changer-le-visuel-des-boutons-dans-la-maintenance-puisquon-ne-peut-plus-cliquer
=> Corrige le style de la situation maintenance

src/public/template_index.html
Le tracking ne fonctionne pas sur le front, je ne pense pas que ça soit la raison mais en creusant je me suis rendu compte que le script matomo a été renommé. C'est déjà correct sur le serveur et le site, il manquait le front.
=> Met à jour le code de suivi Matomo

src/locales/fr.json, src/situations/commun/vues/bouton.js, tests/situations/commun/vues/stop.js
Pour : https://trello.com/c/RcrO09qT/643-on-a-perdu-le-message-de-stop
Bug suite à : https://trello.com/c/vmAssdUb/624-%C3%A9valu%C3%A9-je-peux-cliquer-le-texte-pour-arr%C3%AAter-une-situation
On ne pouvait plus stopper la situation au clic sur arrêter la situation.
Co-authored-by: Clément Prod'homme <clement@captive.fr>
Co-authored-by: Etienne Charignon <etienne.charignon@beta.gouv.fr>
=> Fix le clic sur le bouton arrêter la situation

src/app/index.js, src/situations/accueil/modeles/store.js, src/situations/accueil/vues/formulaire_identification.vue, src/situations/commun/infra/erreur_campagne.js, src/situations/commun/infra/registre_campagne.js, src/situations/commun/infra/registre_utilisateur.js, tests/situations/accueil/modeles/store.js, tests/situations/accueil/vues/formulaire_identification.js, tests/situations/commun/infra/registre_campagne.js, tests/situations/commun/infra/registre_utilisateur.js
Nous avons :
- séparé en deux appels, la récupération de la campagne et de l'evaluation
- créé d'un registre campagne
- ajouté le mode horsligne aux registre des campagnes et des utilisateurs
- géré les erreurs au niveau du store plutôt que la vue du formulaire (peut-être à reprendre)
=> Évalué·e hors-ligne, je peux passer l'écran d'accueil

src/situations/accueil/modeles/store.js, src/situations/commun/infra/registre_campagne.js, tests/situations/accueil/modeles/store.js, tests/situations/commun/infra/registre_campagne.js
On récupère la campagne en locale afin d'éviter un appel inutile et permet de le faire fonctionner quand on a pas de connexion
=> Évalué hors-ligne, je peux voir le parcours

__mocks__/fileMock.js, __mocks__/fileMock_jpg.js, __mocks__/fileMock_png.js, __mocks__/fileMock_wav.js, __mocks__/fileTransformer.js, jest.config.js, package.json, src/app/situation_inventaire.js, src/situations/commun/composants/joueur_audio_buffer.js, src/situations/commun/composants/joueur_consigne.js, src/situations/commun/infra/depot_ressources.js, src/situations/commun/vues/lecteur_audio.vue, src/situations/commun/vues/qcm.vue, src/situations/inventaire/infra/depot_ressources_inventaire.js, src/situations/inventaire/modeles/situation.js, src/situations/inventaire/vues/formulaire_saisie_inventaire.js, src/situations/objets_trouves/infra/depot_ressources_objets_trouves.js, src/situations/objets_trouves/vues/bouton-lecture.vue, src/situations/objets_trouves/vues/lecture-message.vue, tests/situations/commun/aides/mock_chargeurs.js, tests/situations/commun/vues/lecteur_audio.test.js, tests/situations/inventaire/aides/mock_depot_ressources.js, tests/situations/inventaire/vues/formulaire_saisie_inventaire.test.js, tests/situations/objets_trouves/infra/depot_ressources_objets_trouves.test.js, tests/situations/objets_trouves/vues/bouton-lecture.test.js, tests/situations/objets_trouves/vues/lecture-message.test.js
Cette PR supprime les balises <audio> qui ne marchent pas avec Safari dans notre cas.
Safari est apparemment trop exigent quand aux actions utilisateur nécessaires pour jouer un son. Ce commit généralise l'utilisation de `AudioBufferSourceNode`, encapsulé dans le fichier `joueur_audio_buffer.js`.
https://developer.mozilla.org/fr/docs/Web/Guide/Audio_and_video_delivery
Cette PR améliore aussi les tests avec l'usage d'un `fileTransformer.js` pour transformer les ressources sans perdre le nom du fichier (ceci est nécessaire pour s'assurer qu'on a bien charger la bonne ressource dans certains tests).
Voici les 3 écrans qui ne jouaient pas de son sur Safari :
Et sur l'inventaire, on n'entendait pas le "Encore un petit effort" !
=> Fix les sons de la situation "objets trouves" et "inventaire" pour safari

src/situations/accueil/vues/accueil.vue, tests/situations/accueil/vues/accueil.test.js
-> assigne indexBatiment au niveau max même si le chargement des situations à échoué
=> Change de bâtiment automatiquement à la sortie d'une situation

src/situations/accueil/modeles/store.js, src/situations/accueil/vues/accueil.vue, tests/situations/accueil/modeles/store.test.js, tests/situations/accueil/vues/accueil.test.js
A la sortie d'une MES on faisait un appel réseau qui historiquement nous permettait de récupérer la liste des MES. Cette appel réseau est maintenant inutile du fait du horsligne et du stockage des campagnes dans le localstorage.
=> Ne fait plus d'appel réseau au retour à l'accueil

src/situations/commun/infra/report_erreurs.js, webpack.config.js
Avant, l'ensemble des erreurs du client était repertorier dans l'environnement 'production'
=> Différencie les environnements sur Rollbar

src/situations/maintenance/vues/lexique.vue
Certaines tablette ne sont pas identifiés comme mobiles alors on vérifie en plus l'OS
Co-authored-by: Marine Sourin <msourin@captive.fr>
Co-authored-by: Clément Prod'homme <clement@captive.fr>
=> Ajoute la condition de l'OS pour detecter si le device est mobile

src/situations/commun/infra/registre_utilisateur.js, tests/situations/commun/infra/registre_utilisateur.test.js
Il y a un bug qui bloque la mise en production :
Il faut cliquer deux fois sur le bouton de déconnexion
=> Corrige la déconnexion

src/situations/accueil/vues/acces_situation.vue, src/situations/commun/vues/affiche_situation.js
Ceci est necessaire pour que le retour à l'accueil en cas d'abandon
d'une MES redirige bien vers l'url avec un slash à la fin dans le cas du
hors ligne.
=> Ajoute un slash à la fin du SCOP_URL

src/situations/commun/infra/report_erreurs.js
On avait un problème jusque là qui faisait que la console JS ne remontait par les erreurs
Co-authored-by: Étienne Charignon <etienne.charignon@beta.gouv.fr>
=> Retourne les erreurs dans la console JS en environnement de DEV

src/situations/commun/composants/joueur_audio_buffer.js, tests/situations/commun/composants/joueur_audio_buffer.test.js
Cela peut arriver si on lit un son entièrement jusqu'au la fin (ce qui
déclence un appel à la fonction stop()) puis qu'on termine la question ce
qui produit un second appel à stop() dans la méthode beforeDestroy()
de bouton_lecture.vue
Appeler deux fois stop() sur un audio buffer déclenche une erreur
InvalidStateError sur certaine version de safari
https://rollbar.com/eva-betagouv/eva/items/463/?utm_campaign=new_item_message&utm_medium=slack&utm_source=rollbar-notification
=> Permet de stoper un son plusieurs fois sans générer d'erreur

src/public/template_index.html, src/situations/commun/styles/commun.scss
- passe en bleu foncé
- évite d'utiliser la dernière ligne de l'écran qui est parfois
recouverte par des informations du navigateur
=> change légèrement le design de la version dans le footer

tests/situations/accueil/vues/formulaire_identification.test.js
Cette PR supprime un warning à l’exécution des tests
=> Warning test : Ne pas surcharger une prop mais plutôt reconstuire la vue

src/situations/accueil/vues/accueil.vue, tests/situations/accueil/vues/accueil.test.js
Le personnage et la bare de titre s'affichait un brève instant avant
l'affichage de la consigne à cause de la transition "fondue" de cette
dernière.
Avant : 
Après :
=> Évite le glitch lors de l'affichage de la consigne de l'accueil

src/situations/commun/infra/depot_ressources_communes.js, tests/situations/commun/infra/depot_ressources_communes.test.js
Avec le nouveau déploiement, la situation "objets trouvés" ne pouvais plus démarrer. Cette corrige ce problème
https://rollbar.com/eva-betagouv/eva/items/512/?item_page=0&#traceback
=> Corrige le nouveau chargement des illustrations

src/situations/commun/infra/depot_ressources.js, tests/situations/commun/infra/depot_ressources.test.js
J'ai aussi légèrement enrichi un test d'erreur mais ce n'est pas lié au code que j'ai ajouté qui lui n'est pas testé. J'ai fais le test à la main 😞
=> ajoute le nom du fichier lors d'une erreur de décodage audio

src/situations/accueil/modeles/store.js, tests/situations/accueil/modeles/store.test.js
Fix l'erreur rollbar https://rollbar.com/eva-betagouv/eva/items/506/
Pour une raison obscure certains clients n'ont pas de campagne courante.
C'est peut-être qu'ils ont simplement une ancienne version de
l'application, mais ça peut être tout un tas d'autre chose. Bref, pour
éviter d'avoir un plantage, nous forçons ici la déconnexion s'il n'y a
pas de campagne courante.
=> se déconnecte s'il n'y a pas de campagne courante

src/situations/cafe_de_la_place/data/defis.js
=> Ajout des espaces insécables devant les ponctuations doubles

src/situations/cafe_de_la_place/styles/texte_a_trous.scss
=> Fixe la couleur de l'affichage du mot cuisine dans le texte à trou

src/situations/commun/vues/defi/champ_saisie.vue
Le comportement par défaut des 3 propriétés (autocomplete, autocorrect et spellcheck) est à true.
⚠️ vérifier le comportement du champ de saisi sur tablette
=> retirer la correction automatique sur le champ de saisi

src/situations/plan_de_la_ville/styles/drag_and_drop.scss
Sur tablette, il est très facile de "perdre" la maison derrière la consigne.
En ajoutant un z-index sur la maison, on s'assure que la maison reste devant la consigne et permet ainsi de ne pas la perdre
=> Prise en main : empêcher de perdre la maison derrière la consigne

src/situations/cafe_de_la_place/styles/puzzle.scss
pour correspondre à la maquette
avant : 
après :
=> HPar1 : Augmente la taille en hauteur de la zone de dépot

src/situations/cafe_de_la_place/data/parcours_bas.js, src/situations/commun/vues/defi/champ_saisie.vue, src/situations/objets_trouves/data/apps.js, src/situations/plan_de_la_ville/data/defis.js, tests/situations/commun/vues/defi/champ_saisie.test.js
La valeur des scores sera peut-être à ajuster car le travail de
définition est encore en cours. Je me suis basé sur les informations qui
étaient définies jusqu'a présent, qui sont suffisante pour pouvoir
démontrer qu'on calcule bien le profile de production coté serveur.
On permet maintenant à `champ_saisie` d'accepter plusieurs réponses et de donner un score différent à chaque réponse.
=> Ajoute les scores de production de texte

src/situations/commun/infra/registre_utilisateur.js, tests/situations/commun/infra/registre_utilisateur.test.js
TypeError: null is not an object (evaluating 'Object.keys(window.localStorage)')
dans `src/situations/commun/infra/registre_utilisateur.js` line 99 
ne pas faire d'erreur à cet endroit si le localstorage n'est pas disponible.
_Exemple : screenshot, vidéo, scénario pour reproduire_
* https://rollbar.com/eva-betagouv/eva/items/584/
=> Ne fait pas d'erreur si le localStorage n'est pas disponible

src/situations/cafe_de_la_place/data/parcours_haut.js, src/situations/cafe_de_la_place/vues/components/email_HPfb_a_trous.vue, tests/situations/cafe_de_la_place/vues/components/email_HPfb_a_trous.test.js
Cette PR change implémentation du changement de page du mail pour utiliser un `v-if`.
J'ai aussi nettoyé l'import du composant `TrouACompleter` dans `email_HPfb_a_trous.vue` qui était inutile.
=> HPfb : Change l'implémentation de l'affichage des pages de l'email

src/situations/commun/vues/defi/champ_saisie.vue, tests/situations/commun/vues/defi/champ_saisie.test.js
`autofocus` en css ne marche pas avec firefox sur `/jeu/cafe_de_la_place.html#HPfb1`
Pas de focus sur le champ texte sur firefox
Si on est sur firefox, on utilise `.focus()` en javascript sur le champ texte. 
[preventScroll](https://developer.mozilla.org/fr/docs/Web/API/HTMLElement/focus) ne marche pas sur safari. Cela donne un interêt d'utiliser `.focus()` uniquement sur firefox. Et de laisser `autofocus` fonctionner autrement.
=> Ajout du focus si le navigateur est firefox

src/situations/commun/styles/defi/champ_saisie.scss
=> l'outline sur des bords arrondis n'est pas suporté par Safari

src/situations/cafe_de_la_place/data/parcours_haut.js
=> fix affichage de la sous consigne d'hpfb avec la première partie du texte

src/situations/commun/styles/actions.scss, src/situations/commun/styles/boutons.scss, src/situations/commun/styles/conteneur.scss, src/situations/commun/styles/mixins/boutons.scss, src/situations/commun/vues/stop.js, tests/situations/commun/vues/stop.test.js
20% des évalués utilisent une résolution de 1366x768.
Ils doivent scroller pour utiliser le jeu, on peut qu'il n'ait plus besoin de scroller.
On a modifié la barre suivant la maquette présente sur Figma.
Le bouton principal pour entrer dans une situation n'était pas présent sur la maquette, j'ai donc adapté au mieux.
On a fait en sorte que la popup de confirmation de sortie d'une situation ne soit pas placé dans le bloc `.actions` mais dans le bloc `#cadre` afin d'éviter un héritage css un peu bizarre.
Co-authored-by: Marine Dominé <marine@captive.fr>
=> 💄 Réduit la hauteur de la barre d'actions

src/locales/fr.json, src/situations/accueil/vues/index.vue, src/situations/accueil/vues/overlay_erreur.vue, src/situations/commun/styles/modale.scss, tests/situations/accueil/vues/index.test.js, tests/situations/accueil/vues/overlay_erreur.test.js
J'ai mis un overlay opaque comme pour le message d'erreur lecture son car la vue derrière n'est pas le jeu mais l'espace de login.
Exemple du message d'erreur de lecture son
=> Affiche message d'erreur non bloquant pour l'utilisation d'un smartphone

src/situations/accueil/vues/index.vue, src/situations/commun/helpers/mobile.js, src/situations/commun/vues/components/choix_bidirectionnel.vue, src/situations/plan_de_la_ville/data/defis.js, tests/situations/accueil/vues/index.test.js, tests/situations/commun/vues/components/choix_bidirectionnel.test.js
Dans cette PR, j'ai également rajouté un commit pour changer le nom du helper `estMobile` en `estSmartphoneOuTablette` qui m'a induit en erreur lors du développement du message d'erreur pour smartphone, pour plus de précision.
=> Fix ne renvoie pas le message d'erreur smartphone pour tablette

src/situations/accueil/vues/formulaire_donnees_complementaires.vue, tests/situations/accueil/vues/formulaire_donnees_complementaires.test.js
Les seules erreurs possibles sont des erreurs inattendues (erreurs réseau ou autre). Il n'y a aucun cas d'erreur de données à afficher sur le formulaire.
Le serveur retourne maintenant une erreur 500 si l'on n'envoie pas les bonnes valeurs pour les champs de sélection. Ces erreurs sont juste remontées pour être récupéré sur Rollbar.
=> Nouvelle gestion des erreurs du formulaires de données sociodémographiques

src/situations/accueil/modeles/store.js, tests/situations/accueil/modeles/store.test.js, tests/situations/commun/infra/registre_utilisateur.test.js
https://rollbar.com/eva-betagouv/eva/items/655/
Les utilisateurs qui sont sur le formulaire de données sociodémographique après avoir attendu trop longtemps ont une erreur parce que la déconnexion n’a pas été gérée.
Si l’utilisateur recharge la page, il peut même démarrer un parcours alors qu'aucune donnée ne peut être enregistrée.
=> Gère la déconnexion du bénéficaire dans le formulaire de données sociodemographiques

src/situations/inventaire/vues/contenu.js, src/situations/plan_de_la_ville/vues/components/drag_and_drop.vue, tests/situations/plan_de_la_ville/vues/components/drag_and_drop.test.js
Erreur rollbar : `TypeError: this.$refs.cercleBleu.classList.replace is not a function`
La méthode `classList.replace` est normalement bien supportée sur tous les navigateurs dont Chrome Android
https://developer.mozilla.org/en-US/docs/Web/API/Element/classList
Du coup c'est peut-être le chargement de l'image qui a posé problème lors de l'utilisation de la méthode. Je propose donc de s'assurer qu'elle est présente pour lancer l'aimation.
=> Remplace classList.replace pour éviter d'envoyer une erreur quand le navigateur ne supporte pas la méthode

package-lock.json
En particulié :
Follow Redirects improperly handles URLs in the url.parse() function
Package : follow-redirects
Affected versions : < 1.15.4
Patched version : 1.15.4
Versions of the package follow-redirects before 1.15.4 are vulnerable to Improper Input Validation due to the improper handling of URLs by the url.parse() function. When new URL() throws an error, it can be manipulated to misinterpret the hostname. An attacker could exploit this weakness to redirect traffic to a malicious site, potentially leading to information disclosure, phishing attacks, or other security breaches.
=> Actualisation des dépendences

package-lock.json, package.json, webpack.config.js
Précédemment, on utilisait le SHA du commit, mais cela ne permet pas de référencer les versions de manière relative.
Avec cette modification, il est possible de dire : « Vérifier que votre version est plus récente que la version v20240328 ».
=> Utilise le tag git de la release comme version de l'application

package-lock.json, package.json, webpack.config.js
Ça ne marche pas car le build Scalingo ne se fait pas dans un dépôt git, mais dans un snapshot de la version.
=> Revert "Utilise le tag git de la release comme version de l'application"

src/situations/cafe_de_la_place/modeles/store.js, src/situations/cafe_de_la_place/vues/components/multi_select_mixin.js, src/situations/cafe_de_la_place/vues/components/puzzle.vue, src/situations/commun/vues/defi.vue, src/situations/commun/vues/defi/qcm.vue, src/situations/place_du_marche/modeles/store.js, tests/situations/cafe_de_la_place/vues/components/clic_sur_mot.test.js, tests/situations/cafe_de_la_place/vues/components/multi_select_mixin.test.js, tests/situations/commun/vues/defi/qcm.test.js, tests/situations/place_du_marche/modeles/store.test.js
on envoie 0 par défaut quand la question est fausse. Le fait de mettre 0 était une logique présente avant dans le back :
https://github.com/betagouv/eva-serveur/blob/f83430d1c711ede65016ee936212600a0f55db53/app/models/restitution/export_cafe_de_la_place.rb#L48
=> 🐛 Corrige le score envoyé lors de la sélection de la réponse

src/situations/place_du_marche/modeles/store.js, tests/situations/place_du_marche/modeles/store.test.js
Bug détecté grâce à l'erreur rollbar :
https://app.rollbar.com/a/eva-betagouv/fix/item/eva/940?utm_campaign=new_item_message&utm_medium=slack&utm_source=rollbar-notification
À la fin d'un niveau sans passer le rattrapage avec un % de réussite > 70 et < 100, on était redirigé vers le niveau suivant puis à la fin de la situation on devait passer le rattrapage présupposé que l'on aurait dû passer si on avait eu un % de réussite < à 70.
Solution implémenté : Réinitialiser les rattrapages à passer à la fin d'un niveau.
=> 🐛 Réinitialise rattrapages à passer à la fin d'un niveau avec un % de réussite > 70 et avant de passer au niveau suivant

docs/tech-dive-in/EVA-171-le-joueur-utilise-automatiquement-le-parametrage-de-sa-question-qcm-numeratie/readme.md, src/situations/place_du_marche/modeles/store.js, src/situations/place_du_marche/vues/place_du_marche.vue, tests/situations/place_du_marche/modeles/store.test.js
Je n'ai pas fait de migration pour dupliquer toutes les questions numératie sur le back qu'on a déjà créé côté front suite au commentaire de Stéphane:
"en fait dans mon idée tu peux ajouter si tu veux, par contre elle ne serait prise en compte que si tu saisis le bon "code technique" (ou je ne sais plus comment ça s'appelle)"
Avec ce ticket, on peut créer une nouvelle QuestionQcm sur l'admin avec le bon nom_technique et si elle se trouve parmi les questions numératie qu'on a déjà paramétré côté front, alors le paramétrage du back est utilisé.
Tant qu'on a pas créer toutes les question numératie sur le back, la feature continue de fonctionner.
https://github.com/user-attachments/assets/eb818b52-2dfc-4770-8759-ad389754ae5e
https://github.com/user-attachments/assets/81a99275-515a-449d-ac70-ea …
=> Le joueur utilise automatiquement le paramétrage de sa question QCM numératie

src/situations/commun/infra/depot_ressources.js, src/situations/commun/vues/question_entete.vue, tests/situations/commun/vues/question_entete.test.js
=> Affiche le gros bouton lecture si la question a un audio_intitule sans écrit

src/locales/fr.json
Dans la phrase
« Vos informations nous serviront… »
Le « nous » n'est pas un pronom personnel ! :-) (Je fais le malin, mais je ne sais pas en dire beaucoup plus).
=> Corrige une faute d'accord dans le message d'accueil de bienvenue

src/situations/commun/vues/question_entete.vue
J'ai juste appliqué des refactoring sur les conditions et j'ai exploité le fait que `this.demarreSonBouton('boutonLectureQuestionAudio');` peut être appelé même s'il n'y a pas de boutonLectureQuestionAudio.
=> Simplification du code du démarrage initial des sons d'une question

webpack.config.js
Ajoute crossorigin="use-credentials" dans le manifest.json
https://www.outsystems.com/forums/discussion/86597/pwa-app-resources-are-blocked-due-to-cors/
=> 🐛 Le jeu ne lance pas quand certains assets (mp3) ne sont pas chargés

src/situations/cafe_de_la_place/infra/depot_ressources_cafe_de_la_place.js, src/situations/commun/infra/depot_ressources_communes.js, src/situations/place_du_marche/infra/depot_ressources_place_du_marche.js, tests/situations/commun/infra/depot_ressources_communes.test.js
Ces ressources étaient faites dans "depot_ressources_commune" et donc, faites au moment de l'affichage de l'accueil.
Avec ce refactoring, ces ressources sont maintenant chargées seulement au moment du démarrage de la situation concernée
=> ♻️ Remonte l'initialisation des ressources de cafe_de_la_place et place_du_marche

package-lock.json, package.json
Peut être utilisé dans nvim pour améliorer la coloration, la navigation et la completion du code javascript
Configuration :
```
local capabilities = require('cmp_nvim_lsp').default_capabilities()
local lsp_config = require('lspconfig')
local servers = {
eslint = {
cmd = { "node_modules/vscode-langservers-extracted/bin/vscode-eslint-language-server", "--stdio" },
on_attach = function(client, bufnr)
vim.api.nvim_create_autocmd("BufWritePre", {
buffer = bufnr,
command = "EslintFixAll",
})
end,
},
}
for server, config in pairs(servers) do
-- Merge capabilities with server-specific config
config.capabilities = capabilities
lsp_config[server].setup(config)
end
```
=> Ajoute la gem vscode-langservers-extracted pour nvim

src/situations/commun/vues/components/clic_dans_image.vue
Cela fait suite au renommage de image_au_clic en image_au_clic_url coté back
=> 🐛 Renomme image_au_clic par image_au_clic_url afin de fixer l'affichage du curseur dans les questions clic sur image

src/situations/place_du_marche/styles/glisser_deposer.scss
Quand on tente de placer un élément dans un padding, cela place l'élément au début de la liste
https://captive-team.atlassian.net/browse/EVA-337
Exemple d'exercice à vérifier pour s'assurer du fonctionnement : 
- N1Ron1 (Place du marché)
- N3Pum3 (Place du marché)
- N2Prh1 (Place du marché)
- HPar1 (Café de la place)
=> 🐛 Corrige un glitch sur le glisser-deposer

src/situations/commun/vues/components/clic_dans_image.vue, tests/situations/commun/vues/components/clic_dans_image.test.js
Quand je déselectionne une image, je dois recalculer le score
Avant on ne le faisais, ce qui fait que si on sélectionne les bonnes réponses, puis qu'on les déselectionnes, puis on valide (sans rien), alors on a le meilleur score
https://captive-team.atlassian.net/browse/EVA-353
=> 🐛 Questions clic dans l'image - Dernier état non pris en compte en cas de déselection
