betagouv/eva

.gitignore
all-tests.js
package-lock.json
package.json
src/app/index.js
tests/simple-test.js
webpack-test.config.js
webpack.config-test.js

Voici la configuration pour faire des tests avec webpack.
Je n'ai pas réussi à corriger le fait que webpack s'arrête quand un test échoue alors qu'il est pourtant bien lancé en mode "watch". 
Pour l'instant j'ai trouvé comme parade : 
while true; do npm test; sleep 5; done;
Il est aussi possible de lancer mocha en mode watch en ajoutant --watch sur la ligne de commande mocha dans le fichier de configuration webpack. Cela semble fonctionner, mais à chaque nouvelle execution, le nombre de tests augmente.

Test avec webpack

---

.gitignore
README.md
all-tests.js
package-lock.json
package.json
server.js
src/app/index.js
src/app/init.js
src/modeles/magasin.js
tests/aides/magasin.js
tests/app/init.js
tests/modeles/magasin.js
webpack.config-test.js
webpack.config.js

Cette PR ajoute le linter `semistandard` sur le projet puis dans un deuxième commit, corrige toutes les erreurs trouvées sur master.
- Une documentation a été ajouté dans le README
- Des scripts ont été ajouté pour lancer le linter avant les tests, ainsi que tout seul.

Ajoute un linter sur le projet

---

src/app/formulaireSaisieInventaire.js
src/styles/commun.scss
src/styles/formulaireSaisieInventaire.scss
src/styles/overlay.scss
tests/app/formulaireSaisieInventaire.js

Cette PR contribue à l'issue #3.

Ferme le formulaire quand on clique en dehors

---

README.md

Ajoute l'exigence de lintage dans le README.md

---

src/app/init.js
src/styles/commun.scss
src/styles/formulaireSaisieInventaire.scss
src/vues/formulaireSaisieInventaire.js
tests/modeles/magasin.js
tests/vues/formulaireSaisieInventaire.js

Cette PR contribue à l'issue #3.
Le message d'évaluation est pour l'instant un _fake_, et indique toujours un succès, indépendamment des valeurs saisies dans le formulaire.

Valider pour de faux

---

src/app/init.js
src/modeles/inventaireReference.js
src/modeles/magasin.js
src/vues/formulaireSaisieInventaire.js
tests/modeles/inventaireReference.js
tests/modeles/magasin.js

Cette PR contribue (et clôt) l'issue #3.

Valider saisie inventaire

---

src/app/situationInventaire.js
src/modeles/inventaireReference.js
src/vues/formulaireSaisieInventaire.js
tests/modeles/inventaireReference.js
tests/vues/formulaireSaisieInventaire.js

Affiche les erreurs pour chaque valeur saisie dans le formulaire

---

src/styles/contenu.scss
src/styles/etageres.scss
src/vues/contenu.js
tests/vues/contenu.js
tests/vues/contenu_unitaire.js
tests/vues/contenu_vrac.js

- Prise en compte du retour de Hubert sur le delai d'ouverture
- élargissement de l'overlay à tout l'écran
- change le curseur pour un doigt pointé quand le contenant est ouvert.

Quelques améliorations à l'ouverture du contenant

---

src/app/index.js
src/app/situationControle.js
src/app/situationInventaire.js
src/situations.js
src/situations/accueil/styles/app.scss
src/situations/accueil/vues/accueil.js
src/situations/commun/styles/commun.scss
src/situations/controle/styles/app.scss
src/situations/inventaire/styles/app.scss
src/situations/inventaire/styles/formulaireSaisieInventaire.scss
src/situations/inventaire/vues/formulaireSaisieInventaire.js
tests/situations/accueil/vues/accueil.js
webpack.config-test.js
webpack.config.js

Cette PR résout #46 .
_Note : cette PR propose une possible implémentation pour afficher une `situation`, quelque soit cette situation, c'est-à-dire, fixer une taille de zone dans laquelle la situation s'affiche, avec un background par défaut, etc. L'intention est d'étendre cette implémentation à d'autres situations que la situation « Contrôle », notamment la situation « Inventaire »._

Offre accès à la situation « Contrôle »

---

src/app/situationControle.js
src/situations/controle/modeles/piece.js
src/situations/controle/styles/piece.scss
src/situations/controle/vues/piece.js
tests/situations/controle/modeles/piece.js
tests/situations/controle/vues/piece.js
webpack.config-test.js

Cette PR contribue à l'issue #54 
On peut maintenant saisir une pièce, la glisser et la déposer ailleurs.
La pièce apparaît, suit une trajectoire (tapis roulant) et disparaît au bout d'un certain temps.

Affiche une pièce

---

README.md

Il me manquait cette information pour pouvoir tester en local.

Ajout de l'adresse pour accéder a l'instance.

---

config.json
src/situations/inventaire/infra/depot_journal.js
tests/situations/inventaire/infra/depot_journal.js

ajoute méthode pour communiquer avec le serveur

---

src/app/situationControle.js
src/situations/commun/styles/commun.scss
src/situations/controle/modeles/piece.js
src/situations/controle/modeles/situation.js
src/situations/controle/styles/piece.scss
src/situations/controle/vues/piece.js
src/situations/controle/vues/situation.js
tests/situations/controle/modeles/piece.js
tests/situations/controle/modeles/situation.js
tests/situations/controle/vues/piece.js
tests/situations/controle/vues/situation.js

Affiche sequence pieces

---

bin/deploy.sh
bin/prod_deploy.sh

Cela répare le déploiement pour le moment.

Copie du fichier config.json au moment du deploiement.

---

src/app/index.js
src/app/restitutionSituationInventaire.js
src/app/situationControle.js
src/app/situationInventaire.js

Il est important pour moi d'avoir un titre dans toutes les pages de l'application.
J'ai préféré utiliser `document.title` qui fait cela plus facilement qu'utiliser jquery.

Ajout du titre dans toutes les pages.

---

src/app/index.js
src/app/situationControle.js
src/app/situationInventaire.js
src/public/template_index.html
src/situations/accueil/styles/app.scss
src/situations/accueil/vues/accueil.js
src/situations/commun/styles/bouton.scss
src/situations/commun/styles/cadre.scss
src/situations/commun/styles/commun.scss
src/situations/commun/styles/conteneur.scss
src/situations/commun/styles/couleurs.scss
src/situations/controle/styles/app.scss
src/situations/inventaire/styles/app.scss
tests/situations/accueil/vues/accueil.js

Nouvel accueil

---

README.md

Suite a la rétro, j'ai rajouté le lien vers le projet github.

Ajoute le lien vers le projet github.

---

package-lock.json
package.json
src/app/index.js
src/app/restitutionSituationInventaire.js
src/app/situationControle.js
src/app/situationInventaire.js
src/locales/fr.json
src/situations.js
src/situations/commun/infra/internationalisation.js
src/situations/commun/vues/go.js
src/situations/commun/vues/modale.js
src/situations/commun/vues/stop.js
src/situations/inventaire/vues/formulaireSaisieInventaire.js
src/situations/inventaire/vues/situation.js
tests/situations/commun/vues/stop.js

J'ouvre cette pull request pour discuter de l'intérêt ou non d'extraire les chaînes de caractères affichées aux utilisateur·trice·s. 
J'ai utilisé la bibliothèque https://github.com/i18next/i18next. 
Je n'ai pas essayé de brancher sur les différentes situations et ou d'extraire les chaines dans un fichier json. C'était pas mon but. 
Bref, qu'en pensez vous ?

Extraction des chaines de caractères grâce à i18next

---

src/app/index.js
src/app/restitutionSituationInventaire.js
src/app/situationControle.js
src/app/situationInventaire.js
src/situations.js
src/situations/commun/infra/internationalisation.js
src/situations/commun/vues/go.js
src/situations/commun/vues/modale.js
src/situations/commun/vues/stop.js
src/situations/inventaire/vues/formulaireSaisieInventaire.js
src/situations/inventaire/vues/situation.js

Je propose qu'on nomme les « commandes » (les appels qui entraînent un effet de bord) avec des verbes à l'impératif, et les « requêtes » (calculs sans effet de bord) avec des noms communs.

Corrige typo

---

src/app/restitutionSituationInventaire.js
src/app/situationControle.js
src/app/situationInventaire.js
src/situations/commun/infra/depot_journal.js
src/situations/commun/modeles/journal.js
tests/situations/commun/infra/depot_journal.js
tests/situations/commun/modeles/journal.js

… Afin de différencier les événements « Stop » de deux situations différentes.
(… et corrige #92 au passage.)

Injecte le nom de la situation dans le journal

---

src/situations/controle/vues/situation.js

Ce bout de code avait été factorisé, mais les noms de variable était resté inchangés.

Renomme variables

---

package-lock.json
package.json
src/public/template_index.html
src/situations/accueil/styles/app.scss
webpack.config.js

Fix #88 
Intègre font-awesome sur la page d'accueil avec le package npm.

Intègre font-awesome avec le package npm.

---

webpack.config-test.js
webpack.config.js

En lieu et place de `file-loader`.

Utilise url-loader pour les polices et les svgs.

---

src/app/situationInventaire.js
src/situations/commun/modeles/situation.js
src/situations/commun/vues/go.js
src/situations/controle/modeles/situation.js
src/situations/inventaire/modeles/situation.js
src/situations/inventaire/vues/formulaireSaisieInventaire.js
src/situations/inventaire/vues/situation.js
tests/situations/commun/modeles/situation.js
tests/situations/commun/vues/go.js
tests/situations/inventaire/aides/magasin.js
tests/situations/inventaire/vues/situation.js

Cette PR contribue à l'issue #98 
Dans le but de pouvoir intégrer la vueGo dans la VueCadre et que celle-ci puisse jouer aussi pour la situation contrôle, il est nécéssaire d'ajouter un mécanisme d'événements dans le modèle Situation.
En effet, une fois ce mécanisme en place, la vue contrôle pourra s'enregistrer à l'événement démarrage pour lancer le début de la situation. (a venir dans la PR suivante).

Création d'un modele "situation observable"

---

src/situations/commun/modeles/situation.js
src/situations/commun/vues/go.js
src/situations/inventaire/vues/situation.js
tests/situations/commun/modeles/situation.js
tests/situations/commun/vues/go.js
tests/situations/inventaire/vues/situation.js

Cette PR participe à l'issue #98 
- Supprime le journal de la vue Go
- Inscrit le journal à l'événement démarrage dans la vueSituationInventaire

Inscrit le journal à l'événement démarrage

---

src/situations/inventaire/vues/formulaireSaisieInventaire.js
tests/situations/inventaire/vues/formulaireSaisieInventaire.js

[Inventaire] Désactive l'auto completion dans le formulaire de réponse

---

src/situations/inventaire/data/stock.js
src/situations/inventaire/modeles/situation.js
tests/situations/inventaire/aides/magasin.js
tests/situations/inventaire/modeles/magasin.js

affiche les produits triés dans le formulaire de saisie de l'inventaire

---

src/app/situationControle.js
src/app/situationInventaire.js
src/situations/commun/vues/actions.js
src/situations/commun/vues/cadre.js
src/situations/commun/vues/stop.js
tests/situations/commun/vues/actions.js
tests/situations/commun/vues/cadre.js
tests/situations/commun/vues/stop.js

Exporte les classes par défaut dans situations/commun/vues/.
Contribue à #131

Utilise 'export default' dans commun/vues/

---

src/public/template_index.html
src/situations/commun/styles/commun.scss
src/situations/commun/styles/font_awesome.scss

Changer le lien code source en un bouton github

---

src/app/index.js
src/situations/commun/vues/cadre.js

... même quand on a un petit écran

[CORRECTION] Rend le bouton github toujours visible

---

src/app/index.js
src/app/situationControle.js
src/app/situationInventaire.js
src/locales/fr.json
src/situations/accueil/vues/accueil.js
src/situations/accueil/vues/formulaire_identification.js
src/situations/commun/infra/depot_journal.js
src/situations/commun/infra/registre_utilisateur.js
src/situations/commun/modeles/journal.js
tests/situations/accueil/vues/accueil.js
tests/situations/accueil/vues/formulaire_identification.js
tests/situations/commun/infra/depot_journal.js
tests/situations/commun/modeles/journal.js

Nous avons rajouté un formulaire (basique) dans la page d'accueil qui permet à l'évalué·e de rentrer son nom. 
Ce nom est ensuite enregistré dans chaque événement des situations.
Ici, l'utilisateur s'appelle **Roger**:
Contribue à #155

Identification de l'évalué·e

---

src/situations/controle/vues/situation.js
tests/situations/controle/vues/situation.js

Enregistre l'événement de démarrage dans la situation controle.

---

src/app/situationControle.js

La cadence dans le scénario est plus proche des 5s que de 3s. Pour le
test utilisateur ce sera plus proche du scénario final.
Contribue à #148
Co-authored-by: Stéphane Hanser <stephane.hanser@beta.gouv.fr>

Passe la cadence d'arrivée à 5s.

---

src/public/template_index.html
src/situations/commun/styles/commun.scss

Changer le bouton en marque-page

---

src/app/situationControle.js
src/app/situationInventaire.js
src/situations/commun/infra/depot_journal.js
src/situations/commun/modeles/journal.js
tests/situations/commun/infra/depot_journal.js
tests/situations/commun/modeles/journal.js

Utilise l'export par défaut dans les classes commune

---

src/app/situationInventaire.js
src/situations/inventaire/modeles/contenant.js
src/situations/inventaire/modeles/situation.js
src/situations/inventaire/vues/contenant.js
src/situations/inventaire/vues/contenants.js
src/situations/inventaire/vues/contenu.js
src/situations/inventaire/vues/etageres.js
src/situations/inventaire/vues/situation.js
tests/situations/inventaire/aides/magasin.js
tests/situations/inventaire/modeles/magasin.js
tests/situations/inventaire/vues/contenant.js
tests/situations/inventaire/vues/contenants.js
tests/situations/inventaire/vues/contenu.js
tests/situations/inventaire/vues/etageres.js
tests/situations/inventaire/vues/formulaireSaisieInventaire.js
tests/situations/inventaire/vues/situation.js

Inventaire:  Utilise l'export par défaut des classes

---

package-lock.json
package.json
src/public/favicon.svg
webpack.config.js

Ajoute une favicon

---

src/situations/commun/styles/stop.scss

baisse l'opacité du background sur l'écran Stop

---

src/app/index.js
src/situations/accueil/vues/accueil.js
tests/situations/accueil/vues/accueil.js
tests/situations/commun/aides/mockDepot.js
tests/situations/commun/modeles/journal.js

Utilise l'export de classe par défaut pour 2 classes

---

src/app/situationControle.js
src/situations/controle/modeles/bac.js
src/situations/controle/modeles/piece.js
src/situations/controle/modeles/situation.js
src/situations/controle/vues/bac.js
src/situations/controle/vues/piece.js
src/situations/controle/vues/situation.js
tests/situations/controle/modeles/bac.js
tests/situations/controle/modeles/piece.js
tests/situations/controle/modeles/situation.js
tests/situations/controle/vues/bac.js
tests/situations/controle/vues/fond_sonore.js
tests/situations/controle/vues/piece.js
tests/situations/controle/vues/situation.js
tests/situations/controle/vues/tapis.js

Controle: utilise l'export de classe par défaut pour les modèles et les vues

---

src/app/situationControle.js
src/situations/controle/styles/piece.scss
src/situations/controle/vues/piece.js

Grossit les biscuits bonhommes de la situation contrôle

---

package-lock.json
package.json
src/app/situationControle.js
src/app/situationInventaire.js
webpack.config-test.js
webpack.config.js

L'intention est de pouvoir simplifier ensuite le code du `ChargeurRessources` en évitant d'avoir à traiter le cas des data-url pour les fichiers inlinés de taille inférieure à 8k.

Utilise le file loader plutôt que l'URL loader

---

src/app/situationControle.js
src/app/situationInventaire.js
src/situations/commun/vues/affiche_situation.js

Évite de répéter des choses dans le démarrage des situations « Contrôle » et « Inventaire ».

Factorise l'affichage des situations.

---

src/situations/commun/modeles/evenement_rejoue_consigne.js
src/situations/commun/vues/actions.js
src/situations/commun/vues/rejoue_consigne.js
tests/situations/commun/modeles/evenement_rejoue_consigne.js
tests/situations/commun/vues/rejoue_consigne.js

Journalise l'action de rejouer la consigne

---

src/situations/commun/infra/depot_ressources.js

Renomme ressources en cloneursRessource dans la classe DepotRessources.

---

src/locales/fr.json
src/situations/commun/styles/bouton.scss
src/situations/commun/styles/couleurs.scss
src/situations/commun/vues/bouton.js
src/situations/commun/vues/rejoue_consigne.js
src/situations/commun/vues/stop.js
tests/situations/commun/vues/bouton.js

Ajoute une étiquette aux boutons de la barre d'action

---

src/situations/commun/vues/go.js
src/situations/commun/vues/rejoue_consigne.js
tests/situations/commun/vues/rejoue_consigne.js

Le problème était l'enregistrement de multiple écouteurs de l'événement de fin de lecture. 
Fix #252

Corrige l'apparition multiple du bouton rejoue consigne

---

src/situations/inventaire/vues/formulaireSaisieInventaire.js
tests/situations/inventaire/vues/formulaireSaisieInventaire.js

Inventaire: cacher le bouton de retour au stock lorsque la situation est terminée

---

src/locales/fr.json

Pour que le texte de fin soit cohérent entre la situation contrôle et inventaire.

Met à jour le texte de fin de la situation.

---

.env
package.json
src/situations/commun/styles/barre_dev.scss
src/situations/commun/styles/bouton.scss
src/situations/commun/vues/affiche_situation.js
src/situations/commun/vues/barre_dev.js
src/situations/commun/vues/cadre.js
tests/situations/commun/vues/barre_dev.js
tests/situations/commun/vues/cadre.js
webpack.config.js

Reprise de #208.
Pour l'instant la barre ne contient que le bouton début et fin.

Barre d'outils de développement dans les situations

---

src/situations/commun/composants/deplaceur_pieces.js
src/situations/controle/vues/situation.js
src/situations/tri/modeles/situation.js
src/situations/tri/vues/situation.js
tests/situations/commun/composants/deplaceur_pieces.js
tests/situations/controle/vues/situation.js
tests/situations/tri/modeles/situation.js
tests/situations/tri/vues/situation.js

Contribue à #213 
extraie le comportement de déplacement dans une classe à part et l'inclut dans le tri et le contrôle

Tri : déplacement des pièces

---

src/situations/commun/styles/commun.scss

Spécifie une taille de base de la police à 16px.

---

src/situations/commun/vues/cadre.js
src/situations/controle/vues/situation.js
src/situations/inventaire/vues/situation.js
tests/situations/commun/vues/cadre.js
tests/situations/controle/vues/situation.js
tests/situations/inventaire/vues/situation.js

Et donc cela l'envoi nécessairement pour la situation tri.

Envoi l'événement de démarrage de la même manière pour toutes les situations

---

src/situations.js

Maintenant que nous avons quelque chose qui fonctionne de bout en bout, il est temps de l'afficher sur l'accueil !

Affiche le tri sur l'accueil pour tous

---

package-lock.json
package.json
webpack.config-test.js
webpack.config.js

Utilise le plugin Clean de Webpack

---

webpack.config-test.js

… Début d'une opération de nettoyage de nos configs Webpack.

Supprime les clefs inutiles du fichier de config Webpack pour les tests

---

src/situations/controle/infra/depot_ressources_controle.js
src/situations/controle/styles/situation.scss
src/situations/controle/styles/tapis.scss
src/situations/controle/vues/situation.js
src/situations/controle/vues/tapis.js
tests/situations/controle/aides/mock_depot_ressources_controle.js
tests/situations/controle/vues/situation.js
tests/situations/controle/vues/tapis.js

Cela finit la transition au dépôt ressources pour le contrôle et harmonise avec le tri.

Contrôle: utilise le dépôt ressources pour le fond de la situation et le tapis

---

src/situations/inventaire/styles/contenu.scss
src/situations/inventaire/vues/contenu.js
tests/situations/inventaire/vues/contenu.js

Corrige la taille du calque lorsque l'on ouvre un contenant.

---

Dockerfile
conf/nginx.conf

- gzip est activé
- les autres entêtes de cache sont configuré

Spécifie une configuration nginx pour optimiser les assets.

---

src/situations/accueil/styles/accueil.scss

Les bâtiments n'étaient pas exactement à la bonne place.

[CORRECTION] corrige la position des bâtiments de l'accueil

---

src/locales/fr.json
src/situations/accueil/styles/formulaire_identification.scss
src/situations/accueil/vues/accueil.js
src/situations/accueil/vues/formulaire_identification.js
src/situations/commun/infra/registre_utilisateur.js
src/situations/commun/styles/couleurs.scss
tests/situations/accueil/vues/accueil.js
tests/situations/accueil/vues/formulaire_identification.js
tests/situations/commun/infra/registre_utilisateur.js

Accueil: Intégre le nouveau formulaire en overlay

---

src/situations/accueil/styles/formulaire_identification.scss
src/situations/accueil/vues/formulaire_identification.js

Corrige l'alignement du bouton submit dans le formulaire d'identification.

---

src/locales/fr.json
src/situations/commun/styles/couleurs.scss
src/situations/inventaire/styles/formulaire_saisie_inventaire.scss
src/situations/inventaire/vues/formulaire_saisie_inventaire.js
tests/situations/inventaire/vues/formulaire_saisie_inventaire.js

[inventaire] nouvelle mise en forme du résultat de la validation 

---

src/app/situation_controle.js
src/situations/controle/modeles/situation.js

[Contrôle] Ajoute la taille des biscuits du tapis pour qu'ils correspondent exactement au model

---

src/situations/accueil/styles/accueil.scss
src/situations/accueil/vues/accueil.js
src/situations/commun/infra/registre_utilisateur.js
src/situations/commun/styles/boite_utilisateur.scss
src/situations/commun/vues/boite_utilisateur.js
tests/situations/accueil/vues/accueil.js
tests/situations/commun/infra/registre_utilisateur.js
tests/situations/commun/vues/boite_utilisateur.js

ajoute la déconnexion au registre utilisateur

---

src/situations/accueil/styles/accueil.scss

corrige l'affichage de la progression et des personnages sur petit écran

---

tests/situations/controle/modeles/situation.js
tests/situations/controle/vues/fond_sonore.js

Corrige quelques accents dans les tests et remplace une implémentation avec un timeout par quelque chose de plus déterministe dans le tests "joue à l'état DEMARRE".

[Contrôle] Corrige un test instable

---

src/app/index.js
src/situations.js
src/situations/accueil/data/acces_situations.js
src/situations/accueil/modeles/acces_situation.js
src/situations/accueil/styles/acces_situation.scss
src/situations/accueil/styles/accueil.scss
src/situations/accueil/vues/acces_situation.js
src/situations/accueil/vues/accueil.js
tests/situations/accueil/modeles/acces_situation.js
tests/situations/accueil/vues/acces_situation.js
tests/situations/accueil/vues/accueil.js

Cette PR crée une vue AccesSituation pour porter la responsabilité de l'affichage d'un accès à une situation (aujourd'hui sous la forme d'un bâtiment).
- Création de VueAccesSituation
- Prise en charge par la vue de l'activation en fonction du niveau d'avancement de l'evalué·e

[Accueil] Introduction de VueAccesSituation

---

src/situations/accueil/styles/formulaire_identification.scss
src/situations/accueil/vues/accueil.js
src/situations/accueil/vues/formulaire_identification.js
src/situations/accueil/vues/progression.js
src/situations/commun/styles/commun.scss
src/situations/commun/styles/overlay.scss
src/situations/commun/vues/boite_utilisateur.js
tests/situations/accueil/vues/accueil.js
tests/situations/accueil/vues/formulaire_identification.js
tests/situations/accueil/vues/progression.js
tests/situations/commun/vues/boite_utilisateur.js

Cela anéantit toute logique dans la vue accueil pour que sa responsabilité se restreigne à l'initialisation des sous composants et leur placement.

Accueil: Délègue la logique d'affichage/rafraichissement aux sous composants 

---

src/situations/accueil/data/acces_situations.js
src/situations/accueil/vues/accueil.js
src/situations/commun/styles/boite_utilisateur.scss
src/situations/commun/vues/boite_utilisateur.js
tests/situations/accueil/vues/accueil.js
tests/situations/commun/vues/boite_utilisateur.js

[Accueil] Progression dans la boite utilisateur

---

src/app/situation_compte_rendu.js
src/situations/commun/styles/actions.scss
src/situations/compte_rendu/infra/depot_ressources_compte_rendu.js
src/situations/compte_rendu/styles/situation.scss
src/situations/compte_rendu/vues/situation.js
tests/situations/compte_rendu/vues/situation.js

Fix #375 
Et le rendu en fin de situation:
Il manque une vraie consigne, mais elle arrivera plus tard.

Affiche la situation littéracie dans un cadre comme pour les autres mise en situations

---

src/situations/questions/modeles/evenement_reponse.js
src/situations/questions/vues/situation.js
tests/situations/questions/vues/situation.js

J'ai changé son nom en `reponse` et ajouté le nom de la question.

Questions: Change et enrichit l'événement de réponse

---

src/situations/questions/vues/situation.js
tests/situations/questions/vues/situation.js

Questions: Anime la transition des questions et affiche un overlay a la fin

---

.circleci/config.yml

A chaque commit/merge sur master, on déploie l'ensemble de l'application sur `preprod.competences-pro.beta.gouv.fr`.

Ajoute la config de déploiement continue.

---

src/app/index.js
src/situations/accueil/vues/acces_situation.js
src/situations/accueil/vues/formulaire_identification.js
src/situations/accueil/vues/progression.js
src/situations/commun/infra/depot_journal.js
src/situations/commun/infra/registre_utilisateur.js
src/situations/commun/modeles/progression.js
src/situations/commun/vues/boite_utilisateur.js
tests/situations/accueil/vues/acces_situation.js
tests/situations/accueil/vues/accueil.js
tests/situations/accueil/vues/progression.js
tests/situations/commun/infra/registre_utilisateur.js
tests/situations/commun/modeles/progression.js
tests/situations/commun/vues/boite_utilisateur.js

Fix #382
Cette PR est une tentative de séparation en deux de la PR #387

Les situations non accessibles ne font pas progresser l'utilisateur sur l'accueil

---

src/locales/fr.json

Renomme la situation Questions en Bureau.

---

src/situations/accueil/styles/accueil.scss
src/situations/accueil/vues/accueil.vue
src/situations/commun/styles/conteneur.scss
src/situations/commun/styles/couleurs.scss
src/situations/commun/styles/mixins/conteneur.scss
src/situations/commun/styles/mixins/ombre.scss

Se rapproche de la proposition sur Figma : https://www.figma.com/file/DhzjiwvPMUUDAGrDaKrqEEa3/Comp%C3%A9tences-Pro---Master-Sheet?node-id=255%3A0
Contribue à #415

met l'ombre sur la scène

---

src/situations/questions/styles/situation.scss

L'illustration prend désormais tout le fond de la situation.

Passe l'illustration en fond de la situation.

---

src/situations/accueil/vues/accueil.vue
src/situations/accueil/vues/formulaire_identification.vue
tests/situations/accueil/vues/formulaire_identification.js

Co-authored-by: François de Metz <francois.de_metz@beta.gouv.fr>

cache le champ campagne si il y a un paramètre code dans l'url

---

src/situations/commun/styles/boutons.scss
src/situations/commun/styles/couleurs.scss
src/situations/questions/styles/redaction_note.scss
src/situations/questions/styles/situation.scss
src/situations/questions/vues/qcm.js
src/situations/questions/vues/redaction_note.js

A part pour la couleur des radio boutons

prise en compte de la nouvelle DA pour les questions du bureau

---

src/situations/questions/modeles/situation.js
src/situations/questions/styles/situation.scss
src/situations/questions/vues/progression.js
src/situations/questions/vues/situation.js
tests/situations/questions/vues/progression.js
tests/situations/questions/vues/situation.js

Ajoute la puce d'indication de la progression dans les questions du bureau

---

src/situations/commun/styles/action_overlay.scss
src/situations/commun/styles/barre_dev.scss
src/situations/commun/styles/couleurs.scss
src/situations/questions/styles/redaction_note.scss
src/situations/questions/styles/situation.scss

- bouton GO en violet
- Boutons bare de dev en violet
- ajout d'un chapitre "branding & style-guide" dans couleurs.scss

[Bureau] encore un peut d'integration nouvelles couleurcouleur

---

src/locales/fr.json
src/situations/commun/styles/modale.scss

modifie la phrase d'abandon

---

src/locales/fr.json
src/situations/questions/modeles/situation.js
src/situations/questions/vues/qcm.js
src/situations/questions/vues/situation.js
tests/situations/questions/modeles/situation.js
tests/situations/questions/vues/qcm.js
tests/situations/questions/vues/situation.js

[Questions] Affiche le résultat à la fin

---

src/locales/fr.json
src/situations/accueil/styles/formulaire_identification.scss
src/situations/accueil/vues/formulaire_identification.vue
tests/situations/accueil/vues/formulaire_identification.js

Ajoute une case a cocher pour recueillir le consentement des évalué·e·s.

---

src/locales/fr.json
src/situations/accueil/vues/accueil.vue
src/situations/accueil/vues/fin.vue
src/situations/accueil/vues/formulaire_identification.vue
src/situations/commun/vues/transition_fade.vue
tests/situations/accueil/vues/accueil.js
tests/situations/accueil/vues/fin.js

L'appui sur le bouton conclure affiche une modale avec un message de remerciement. L'appui sur le bouton terminer déconnecte l'évalué·e.
Contribue à #402

Accueil: Affiche un écran de fin

---

src/situations/accueil/vues/fin.vue
src/situations/commun/styles/commun.scss
src/situations/commun/styles/modale.scss

La règle de définition des paragraphes des questions était moins prioritaire
que la définition globale posée dans commun.scss

[CORRECTION] corrige le style des paragraphes des questions

---

src/app/situation_controle.js
src/app/situation_inventaire.js
src/app/situation_questions.js
src/app/situation_tri.js
src/situations/commun/styles/action_overlay.scss
src/situations/commun/styles/barre_dev.scss
src/situations/commun/styles/situation.scss
src/situations/commun/styles/stop.scss
src/situations/commun/styles/terminer.scss
src/situations/commun/vues/action_overlay.js
src/situations/commun/vues/actions.js
src/situations/commun/vues/affiche_situation.js
src/situations/commun/vues/stop.js
src/situations/commun/vues/terminer.js
src/situations/inventaire/styles/formulaire_saisie_inventaire.scss
src/situations/inventaire/vues/formulaire_saisie_inventaire.js

Optimise import css

---

src/situations/commun/composants/deplaceur_pieces.js
tests/situations/commun/composants/deplaceur_pieces.js

Corrige le deplaceur pièce pour qu'il supporte de ne pas deplacer de pièce

---

src/situations/securite/data/zones.js
src/situations/securite/vues/fenetre_zone.vue
tests/situations/securite/vues/fenetre_zone.js

Sécurité: Permet d'avoir des zones sans danger.

---

src/locales/fr.json
src/situations/securite/styles/situation.scss
src/situations/securite/vues/situation.vue
tests/situations/securite/vues/situation.js

Sécurité: Affiche un compteur de dangers identifiés.

---

src/situations/securite/store/store.js
src/situations/securite/vues/fenetre_zone.vue
src/situations/securite/vues/formulaire_radio.vue
src/situations/securite/vues/situation.vue
tests/situations/securite/store/store.js
tests/situations/securite/vues/fenetre_zone.js
tests/situations/securite/vues/formulaire_radio.js
tests/situations/securite/vues/situation.js

Sécurité: Une fois qualifié une première fois, on ne peut que requalifier le danger

---

src/locales/fr.json
src/situations/securite/store/store.js
src/situations/securite/styles/fenetre.scss
src/situations/securite/styles/fenetre_aide.scss
src/situations/securite/styles/fenetre_zone.scss
src/situations/securite/styles/situation.scss
src/situations/securite/vues/bouton_aide.vue
src/situations/securite/vues/fenetre_aide.vue
src/situations/securite/vues/fenetre_zone.vue
src/situations/securite/vues/situation.vue
tests/situations/securite/store/store.js
tests/situations/securite/vues/bouton_aide.js
tests/situations/securite/vues/fenetre_aide.js
tests/situations/securite/vues/situation.js

Securité: Ajoute l'aide de niveau 1

---

src/situations/securite/modeles/evenement_activation_aide.js
src/situations/securite/vues/bouton_aide.vue
tests/situations/securite/modeles/evenement_activation_aide.js
tests/situations/securite/vues/bouton_aide.js

Co-authored-by: François de Metz <francois.de_metz@beta.gouv.fr>

Émet un évenement à l'activation de l'aide dans la situation Sécurité

---

src/situations/accueil/vues/formulaire_identification.vue
tests/situations/accueil/vues/formulaire_identification.js

Ré-initialise la case CGU après l'avoir enregistrée

---

src/situations/securite/data/zones.js
src/situations/securite/modeles/evenement_click_hors_zone.js
src/situations/securite/vues/situation.vue
tests/situations/securite/modeles/evenement_click_hors_zone.js
tests/situations/securite/vues/situation.js

Lorsque l'on click sur la situation hors zone, un événement est enregistré.

Sécurité: Enregistre un événement clickHorsZone.

---

src/locales/fr.json

Changement de wording pour supprimer le mot qualifier.

---

src/locales/fr.json
src/situations/accueil/vues/fin.vue
src/situations/commun/styles/fin.scss

Cette PR contrinue a betagouv/competences-pro-www#5

Ecran de fin : Ajoute les liens vers le site vitrine pour les compétences fortes

---

src/locales/fr.json
src/situations/securite/store/store.js
src/situations/securite/vues/fenetre_zone.vue
tests/situations/securite/store/store.js
tests/situations/securite/vues/fenetre_zone.js

Securité: affiche une fenêtre lorsqu'on réouvre une zone de non-danger

---

src/situations/commun/vues/rejoue_consigne.js
tests/situations/commun/vues/rejoue_consigne.js

Ne rejoue pas la consigne commune lorsque l'entrainement a démarré.

---

src/situations/securite/data/zones.js

 [Sécurité] met toutes les zones à la même taille

---

src/situations/accueil/modeles/store.js
tests/situations/accueil/modeles/store.js

Prépare le fait que le serveur puisse en renvoyer plus que deux dans le cadre de la restitution destinée au prescripteur

Récupère les deux compétences les plus fortes, même s'il y en a plus

---

src/locales/fr.json

Corrige une faute d'orthographe dans la consigne de la situation contrôle

---

src/situations/commun/vues/actions.js
src/situations/commun/vues/rejoue_consigne.js
tests/situations/commun/vues/rejoue_consigne.js

Plutôt que comme argument de la méthode `affiche`.

Passse la situation dans le constructeur de rejoue consigne.

---

src/locales/fr.json
src/situations/commun/styles/fenetre_aide.scss
src/situations/inventaire/data/stock.js
src/situations/inventaire/modeles/situation.js
src/situations/inventaire/styles/contenu.scss
src/situations/inventaire/vues/contenu.js
src/situations/inventaire/vues/etageres.js
tests/situations/inventaire/vues/contenu.js

Inventaire: niveau d'aide avec le contenu en tout lettres

---

src/situations/inventaire/styles/formulaire_saisie_inventaire.scss
src/situations/inventaire/vues/formulaire_saisie_inventaire.js
tests/situations/inventaire/vues/formulaire_saisie_inventaire.js

J'ai également nettoyé du code qui n'est plus nécessaire avec l'overlay de fin qui recouvre tout.
Fix #567

Inventaire: mise à jour du style de l'overlay de saisie de l'inventaire.

---

src/locales/fr.json
src/situations/commun/styles/boutons.scss
src/situations/inventaire/assets/loupe.svg
src/situations/inventaire/assets/retour.svg
src/situations/inventaire/infra/depot_ressources_inventaire.js
src/situations/inventaire/styles/formulaire_saisie_inventaire.scss
src/situations/inventaire/vues/formulaire_saisie_inventaire.js
tests/situations/inventaire/aides/mock_depot_ressources.js
tests/situations/inventaire/vues/formulaire_saisie_inventaire.js

Inventaire: Ajoute un bouton retour dans la fenêtre de saisie.

---

src/locales/fr.json
src/situations/inventaire/assets/saisie-reponse.svg
src/situations/inventaire/styles/formulaire_saisie_inventaire.scss
src/situations/inventaire/vues/formulaire_saisie_inventaire.js

Inventaire: Change le style du bouton de saisie inventaire.

---

src/situations/commun/vues/cadre.js
tests/situations/commun/vues/cadre.js

Enregistre la situation faite au démarrage de l'entrainement.

---

src/locales/fr.json

Renomme Compétences pro en eva.

---

src/locales/fr.json
src/situations/inventaire/styles/formulaire_saisie_inventaire.scss
src/situations/inventaire/vues/formulaire_saisie_inventaire.js
tests/situations/inventaire/vues/formulaire_saisie_inventaire.js

Et le cache au réaffichage de l'overlay.
Fix #566

Inventaire: Affiche un message d'erreur en cas d'erreur de saisie d'inventaire.

---

src/situations/controle/modeles/evenement_piece_apparition.js
src/situations/controle/vues/situation.js
tests/situations/controle/modeles/evenement_piece_apparition.js
tests/situations/controle/vues/situation.js

Controle: enregistrement de l'événement nouvelle pièce

---

src/situations/commun/modeles/evenement_fin_situation.js
src/situations/commun/vues/cadre.js
tests/situations/commun/modeles/evenement_fin_situation.js
tests/situations/commun/vues/cadre.js

Contribue à la [206](https://github.com/betagouv/competences-pro-serveur/issues/206) côté serveur.

Envoi un événement fin de situation

---

src/situations/accueil/vues/accueil.vue
src/situations/accueil/vues/formulaire_identification.vue
tests/situations/accueil/vues/formulaire_identification.js

pré-rempli le champs nom si il est spécifié dans les paramètres de l'url

---

src/situations/accueil/styles/fin.scss
src/situations/accueil/vues/fin.vue
src/situations/commun/styles/modale.scss

Le formulaire de login avec été impacté par les évolutions de style de l'écran de fin

Fix: réduit le scope d'influence du fichier fin.scss

---

src/locales/fr.json
src/situations/accueil/styles/accueil.scss
src/situations/accueil/vues/accueil.vue
src/situations/commun/vues/stop.js

Supprime le wording "mission" au profit de "situation"

---

README.md

remplace des références Compétences Pro vers eva

---

README.md

Met àjour les commandes dockers dans le readme

---

.circleci/config.yml

renomme competences-pro en eva pour circle ci

---

package-lock.json
package.json

met à jour le nom du projet dans package.json

---

src/locales/fr.json
src/situations/accueil/vues/fin.vue

pour #658
Co-authored-by: Étienne Charignon <etienne.charignon@beta.gouv.fr>

force le retour à la ligne pour afficher le nom sur l'écran de fin

---

src/locales/fr.json

corrige des fautes dans la consigne du tri

---

src/locales/fr.json

Change la consigne d'accueil

---

src/locales/fr.json

met à jour la consigne du contrôle

---

src/locales/fr.json

Met à jour le texte de présentation du potentiel

---

src/locales/fr.json

Met à jour la consigne RGPD

---

src/situations/commun/vues/transition_fade.vue
src/situations/prevention/vues/acte.vue

Prévention: Ajoute une transition sur le fond orange.

---

src/app/situation_maintenance.js
src/situations/maintenance/vues/acte.vue
tests/situations/maintenance/vues/acte.js

Maintenance: Active l'entrainement

---

src/situations/maintenance/data/lexique.js

Contribue à la #704 
Affiche aléatoirement les mots du lexique en configuration normale

Affiche aléatoirement les mots du lexique en configuration normale

---

src/situations/prevention/modeles/store.js
src/situations/prevention/vues/acte.vue
src/situations/prevention/vues/action_prevention.vue
tests/situations/prevention/modeles/store.js
tests/situations/prevention/vues/acte.js

Prévention: Passe la situation en terminé une fois toute les zones traitées

---

src/locales/fr.json

Prévention: ajout de la consigne écrite

---

webpack.config.js

Un petit détail, mais cela m'a interrogé lorsque je regardais le html généré.

Renomme le nom du fichier js de competencesPro à index.

---

src/locales/fr.json
src/situations/commun/styles/boutons.scss
src/situations/commun/styles/modale.scss
src/situations/commun/vues/modale.js
src/situations/commun/vues/stop.js
src/situations/maintenance/assets/fleche_droite.svg
src/situations/maintenance/assets/fleche_gauche.svg
src/situations/maintenance/infra/depot_ressources_maintenance.js
src/situations/maintenance/styles/lexique.scss
src/situations/maintenance/vues/acte.vue
src/situations/maintenance/vues/lexique.vue
tests/situations/maintenance/aides/mock_depot_ressources_maintenance.js
tests/situations/maintenance/vues/acte.js
tests/situations/maintenance/vues/lexique.js

Maintenance: Ajoute les boutons 

---

src/situations/maintenance/modeles/evenement_identification_mot.js
src/situations/maintenance/vues/lexique.vue
tests/situations/maintenance/modeles/evenement_identification_mot.js
tests/situations/maintenance/vues/lexique.js

Dépend de #726 
Contribue à #704

Maintenance: envoi événement identificationMot et correction de bug

---

src/situations/prevention/styles/acte.scss

Le survol d'une zone déjà traité ne changera rien.
Contribue à #669

Empêche toute requalification dans la situation prévention.

---

.circleci/config.yml

En attente de https://github.com/betagouv/eva-orchestrateur/pull/47

Déploie la preprod en déclenchant un build sur l'orchestrateur.

---

src/app/situation_livraison.js
src/locales/fr.json
src/situations/commun/infra/depot_ressources.js
src/situations/commun/infra/registre_utilisateur.js
src/situations/questions/infra/depot_ressources_questions.js
src/situations/questions/vues/situation.js
tests/situations/commun/infra/registre_utilisateur.js
tests/situations/questions/infra/depot_ressources_questions.js
tests/situations/questions/vues/situation.js
webpack.config-test.js
webpack.config.js

La situation Livraison correspond au bureau avec un questionnaire différent. C'est le dépôt ressources qui va s'occuper de récupérer les questions sur le questionnaire de la situation. Le cas du bureau avec un questionnaire associé a la campagne reste valide pour le moment.
Contribue à #748

Création de la situation livraison 

---

src/situations/maintenance/modeles/evenement_apparition_mot.js
src/situations/maintenance/vues/lexique.vue
tests/situations/maintenance/vues/lexique.js

Cet événement va permettre de calculer certaines métriques. 
Notamment les temps moyens de réponses par catégorie.

Ajoute événement apparitionMot

---

src/app/situation_livraison.js
src/situations/commun/vues/transition_fade.vue
src/situations/questions/infra/depot_ressources_questions.js
src/situations/questions/modeles/store.js
src/situations/questions/vues/acte.vue
src/situations/questions/vues/situation.vue
tests/situations/questions/infra/depot_ressources_questions.js
tests/situations/questions/modeles/store.js

Dépend de #752
Contribue à #748

Livraison: ajout de l'entrainement

---

src/situations/prevention/modeles/evenement_evaluation_danger.js
src/situations/prevention/vues/acte.vue
tests/situations/prevention/modeles/evenement_evaluation_danger.js
tests/situations/prevention/vues/acte.js

Prévention: ajoute l'événement d'identification de danger

---

src/locales/fr.json

Ajoute la consigne texte de la livraison.

---

src/situations/commun/styles/boite_utilisateur.scss

Fixe la hauteur du bouton déconnexion

---

src/situations/commun/vues/affiche_situation.js

Redirige l'évalué·e vers la page d'accueil si déconnecté.

---

src/situations/commun/infra/internationalisation.js

Active le mode debug seulement en dévelopement.

---

src/locales/fr.json
src/situations/commun/styles/boite_utilisateur.scss
src/situations/commun/vues/boite_utilisateur.vue
tests/situations/commun/vues/boite_utilisateur.js

Pour éviter les erreurs de manips:

Ajoute une confirmation à la déconnexion

---

src/app/index.js
src/app/situation_controle.js
src/app/situation_inventaire.js
src/app/situation_livraison.js
src/app/situation_maintenance.js
src/app/situation_objets_trouves.js
src/app/situation_prevention.js
src/app/situation_questions.js
src/app/situation_securite.js
src/app/situation_tri.js
webpack.config.js

J'ai détecté au moins le non support des Promesses (ou support incomplet) 
- https://rollbar.com/eva-betagouv/eva/items/77/
- https://rollbar.com/eva-betagouv/eva/items/75/

Ajoute le support de fonctionnalités manquantes dans certains navigateurs

---

src/situations/commun/composants/joueur_consigne.js
src/situations/commun/vues/consigne.vue
tests/situations/commun/composants/joueur_consigne.js
tests/situations/commun/vues/consigne.js

Active le boutons des consignes immediatement et stop le son

---

src/situations/objets_trouves/modeles/store.js
src/situations/objets_trouves/styles/acte.scss
src/situations/objets_trouves/vues/accueil.vue
src/situations/objets_trouves/vues/acte.vue
src/situations/objets_trouves/vues/icone_app.vue
tests/situations/objets_trouves/modeles/store.js
tests/situations/objets_trouves/vues/accueil.js

Désactive les apps qui ont été visitées.

---

src/situations/objets_trouves/data/apps.js
src/situations/objets_trouves/modeles/store.js
src/situations/objets_trouves/styles/acte.scss
src/situations/objets_trouves/vues/accueil.vue
src/situations/objets_trouves/vues/acte.vue
src/situations/objets_trouves/vues/situation.js
tests/situations/objets_trouves/modeles/store.js
tests/situations/objets_trouves/vues/accueil.js
tests/situations/objets_trouves/vues/acte.js

Cette PR permet de configurer la situation avec les apps a afficher et les questions associés. Cela change également un peu l'affichage de l'écran du téléphone.
Contribue à #776

Affiche les apps et les questions à partir de la configuration.

---

src/situations/objets_trouves/vues/accueil.vue
src/situations/objets_trouves/vues/heure.vue
tests/situations/objets_trouves/vues/accueil.js

Pour des raisons évidentes de diégèse, l'heure courante est affiché et mise à jour sur le téléphone.
Note: le screenshot a été pris à 17h49 pour plus d'incompréhension.
Contribue à #776

Objets trouvés: Affiche l'heure courante et la met à jour. 

---

src/situations/objets_trouves/data/apps.js
src/situations/objets_trouves/modeles/store.js
src/situations/objets_trouves/vues/acte.vue
tests/situations/objets_trouves/modeles/store.js
tests/situations/objets_trouves/vues/acte.js

Dépend de #808 
Cette PR ajoute la gestion des question de fin (une fois toutes les apps faites) et le fait de terminer.
Contribue à #776

Objets trouves: Gère la fin

---

src/locales/fr.json
src/situations/accueil/assets/avatar-avis.svg
src/situations/accueil/infra/depot_ressources_accueil.js
src/situations/accueil/styles/fin.scss
src/situations/accueil/vues/fin.vue
src/situations/commun/styles/boutons.scss
src/situations/commun/styles/couleurs.scss
tests/situations/accueil/vues/fin.js

Pour #797 
https://www.loom.com/share/f82b35f7dedd4852850d29d5d9d8bd6c

Propose de donner son avis à la fin du parcours

---

src/app/situation_objets_trouves.js
src/situations/commun/vues/consigne.vue
src/situations/objets_trouves/data/apps.js
src/situations/objets_trouves/infra/depot_ressources_objets_trouves.js
src/situations/objets_trouves/modeles/store.js
src/situations/objets_trouves/vues/acte.vue
tests/situations/objets_trouves/modeles/store.js
tests/situations/objets_trouves/vues/acte.js

Avec Marine nous avons contribué à #776 
Cette PR ajoute l'entrainement pour la situation Objets Trouvés.

Objets Trouvés : Ajoute entraînement

---

src/situations/objets_trouves/vues/acte.vue

Cela corrige une erreur dans les tests.

S'assure qu'on a une question de fin avant d'essayer de l'afficher.

---

src/situations/objets_trouves/data/apps.js

Il me semble qu'il s'agit bien de deux phrases distinctes

Corrige le wording de la question de l'agenda de l'entrainement

---

src/locales/fr.json

Ajoute les consigne texte de la situation objets trouvés.

---

src/locales/fr.json

modifie la consigne de l'entrainement de lost phone

---

src/situations/commun/modeles/evenement_affichage_question_qcm.js
src/situations/commun/vues/qcm.vue
tests/situations/commun/vues/qcm.js

Envoie un événement à l'affichage de chaque question QCM

---

src/locales/fr.json
src/situations/objets_trouves/data/apps.js
src/situations/objets_trouves/modeles/store.js
src/situations/objets_trouves/styles/acte.scss
src/situations/objets_trouves/vues/accueil.vue
tests/situations/objets_trouves/modeles/store.js
tests/situations/objets_trouves/vues/accueil.js

... et centre le texte verticalement.

[Objets Trouvés] Affiche des consignes différentes pour l'écran d'accueil d'entraînement et de situation

---

src/situations/commun/vues/question.vue
src/situations/objets_trouves/styles/acte.scss
tests/situations/commun/vues/question.js

Co-authored-by: Marine Dominé <marine@captive.fr>
Contribue à #776

Ajoute les icônes des applications dans les questions

---

src/situations/objets_trouves/vues/questions_app.vue
tests/situations/objets_trouves/vues/questions_app.js

Envoie les réponses dans la situation objets trouvés

---

src/situations/commun/styles/formulaire_qcm.scss

Ajoute un curseur plus friendly sur les choix des questions.

---

src/locales/fr.json
src/situations/objets_trouves/modeles/situation.js
src/situations/objets_trouves/modeles/store.js
src/situations/objets_trouves/styles/acte.scss
src/situations/objets_trouves/vues/accueil.vue
src/situations/objets_trouves/vues/acte.vue
tests/situations/objets_trouves/vues/accueil.js
tests/situations/objets_trouves/vues/acte.js

Ajoute la transition entre les apps et les questions de fin

---

src/situations/objets_trouves/data/apps.js

Ceci est utile pour s'y retrouver dans les événements enregistrés coté
serveur

Objets trouvés: précise les id des questions de l'appli messages

---

src/situations/commun/vues/question.vue
src/situations/objets_trouves/modeles/store.js
src/situations/objets_trouves/vues/accueil.vue
src/situations/objets_trouves/vues/acte.vue
src/situations/objets_trouves/vues/icone-app-active.vue
src/situations/objets_trouves/vues/icone_app.vue
src/situations/objets_trouves/vues/questions_app.vue
tests/situations/commun/vues/question.js
tests/situations/objets_trouves/modeles/store.js
tests/situations/objets_trouves/vues/acte.js
tests/situations/objets_trouves/vues/icone-app-active.js

Ceci corrige une régression introduite avec l'écran de déverrouillage.

Objets trouvés : passe aux questions de la fin quand toutes les apps ont été visitées

---

src/situations/objets_trouves/data/apps.js

Ceci est en particulier nécessaire pour la question « Avec qui Sophie a
t-elle déjeuné ? » qui s'affiche avec le "?" à la ligne

Objets trouvés : met des espaces insécables devant les points d'interrogation

---

src/situations/objets_trouves/data/apps.js

Objets trouvés: corrige l'affichage de l'écran de dévérouillage

---

src/situations/commun/vues/qcm.vue
src/situations/objets_trouves/data/apps.js
src/situations/objets_trouves/vues/questions_app.vue
src/situations/questions/vues/acte.vue
src/situations/questions/vues/redaction_note.vue
tests/situations/commun/vues/qcm.js
tests/situations/objets_trouves/vues/questions_app.js
tests/situations/questions/vues/acte.js
tests/situations/questions/vues/redaction_note.js

[Objets Trouvés] Envoie les métacompétences et les types réponses au serveur

---

src/situations/objets_trouves/data/apps.js
src/situations/objets_trouves/modeles/store.js
src/situations/objets_trouves/styles/acte.scss
src/situations/objets_trouves/vues/accueil.vue
tests/situations/objets_trouves/modeles/store.js
tests/situations/objets_trouves/vues/accueil.js

Objets trouvés : Gère une liste de messages pour l'écran d'accueil

---

src/situations/objets_trouves/vues/heure.vue

affiche une heure fixe : 13h00

---

src/situations/objets_trouves/data/apps.js

Clarifie le message d'accueil de l'entrainement Agenda

---

src/situations/commun/styles/formulaire_qcm.scss

Corrige l'affichage des radio buttons des questions sur Safari

---

src/situations/commun/vues/qcm.vue
src/situations/objets_trouves/data/apps.js
src/situations/objets_trouves/styles/lecture-message.scss

Fixe #896 
https://www.loom.com/share/0bbd807d03ee4dd4b1e234bce7fa906a

Aide à l'utilisation de l'application répondeur

---

src/situations/objets_trouves/data/apps.js

Objets trouvés: Ajoute dans l'agenda un consigne pour dire qu'il faut cliquer sur les HP

---

src/locales/fr.json

Objets trouvés - Simplification du message de l'écran de transition

---

src/locales/fr.json

Révision de la consigne de la MES Bienvenue

---

package-lock.json
package.json
src/locales/fr.json

Mise en prod de déconfinement 11/05/2020

---

src/situations/bienvenue/infra/depot_ressources_bienvenue.js

Bienvenue - Intégration consigne audio

---

src/situations/commun/styles/formulaire_qcm.scss
src/situations/commun/vues/qcm.vue
src/situations/objets_trouves/styles/acte.scss

Fix #947 
La whitecard fait maintenant 417px de hauteur minimale.
Correction des padding / marges des questions.
Le bouton est toujours ferré en bas de la card.

Met à jour le design de la whitecard

---

src/locales/fr.json
src/situations/accueil/modeles/store.js
src/situations/accueil/styles/formulaire_identification.scss
src/situations/accueil/vues/formulaire_identification.vue
src/situations/commun/infra/registre_utilisateur.js
tests/situations/accueil/vues/formulaire_identification.js

Accueil - Ajoute champs mail et telephone

---

src/situations/commun/modeles/journal.js
tests/situations/commun/modeles/journal.js

Pour : https://trello.com/c/tYEuufE6/148-ajouter-un-champ-num%C3%A9ro-d%C3%A9v%C3%A9nement-c%C3%B4t%C3%A9-client

Ajoute une position pour chaque événement

---

src/situations/inventaire/data/stock.js
src/situations/inventaire/modeles/contenant.js
src/situations/inventaire/styles/situation.scss
src/situations/inventaire/vues/contenant.js
tests/situations/inventaire/vues/contenant.js

pour https://trello.com/c/dP4il9dB/376-inventaire-mettre-en-%C3%A9vidence-au-survol-des-contenants-quon-peut-faire-quelque-chose
La vidéo
https://www.loom.com/share/083d2b9b1b7c4fadbe8495fc6f0e7d02

Affiche un effet de survol dans l'inventaire

---

src/locales/fr.json

Co-authored-by: Etienne Charignon <etienne.charignon@beta.gouv.fr>
Pour : https://trello.com/c/3PNMzUTw/430-inventaire-mettre-litre-au-pluriel-dans-le-tableau-de-saisie

Ajoute un "s" à litre dans la situation inventaire

---

src/situations/accueil/styles/formulaire.scss
src/situations/accueil/vues/formulaire_identification.vue
tests/situations/accueil/vues/formulaire_identification.js

Suite à la mise à jour du serveur avec la PR betagouv/eva-serveur#650, il est nécessaire de mettre à jour l'affiche de l'erreur de code campagne.
J'en profite pour mettre l'erreur en rouge

Nouvelle correction code inconnu

---

src/locales/fr.json

Fix une faute d'orthograhe dans la consigne de transition de maintenance

---

src/situations/accueil/styles/formulaire.scss
src/situations/accueil/vues/formulaire_identification.vue
tests/situations/accueil/vues/formulaire_identification.js

Accueil : Encadre en rouge le champ "Code de campagne" s'il est inconnu

---

src/situations/accueil/modeles/store.js
src/situations/accueil/vues/accueil.vue
src/situations/accueil/vues/fin.vue
src/situations/commun/infra/registre_utilisateur.js
tests/situations/accueil/modeles/store.js
tests/situations/accueil/vues/fin.js
tests/situations/commun/infra/registre_utilisateur.js

Pour le ticket https://trello.com/c/sg6b9eSq
à merger après (ou à la place de) la PR #996
Cette PR appelle la nouvelle api "termine", qui termine une évaluation et retourne les compétences fortes de l'évalué·e.

Termine l'évaluation et affiche les compétences fortes

---

src/situations/accueil/styles/accueil.scss
src/situations/accueil/vues/accueil.vue

Intègre l'annonce générale

---

src/situations/commun/styles/couleurs.scss
src/situations/maintenance/styles/lexique.scss
src/situations/maintenance/styles/touche.scss
src/situations/maintenance/vues/lexique.vue
src/situations/maintenance/vues/touche.vue
tests/situations/maintenance/vues/lexique.js
tests/situations/maintenance/vues/touche.js

Et sur mobile c'est toujours comme avant :

Crée un vue des actions clavier du robot

---

src/locales/fr.json
src/situations/accueil/styles/accueil.scss
src/situations/accueil/vues/accueil.vue
src/situations/commun/styles/aide.scss
src/situations/commun/styles/bouton.scss
src/situations/commun/styles/stop.scss
src/situations/commun/vues/bouton.js
tests/situations/commun/vues/stop.js

Pour : https://trello.com/c/vmAssdUb/624-%C3%A9valu%C3%A9-je-peux-cliquer-le-texte-pour-arr%C3%AAter-une-situation
Boutons modifiés : 
- Situation suivante
- Situation précédente
- Arrêter la situation 
- Répéter la consigne
- Hover bouton aide
https://www.loom.com/share/e3d09523ece8477bae714937b73cb11a

Je peux cliquer sur le texte des boutons d'actions

---

src/app/index.js
src/locales/fr.json
src/situations/accueil/modeles/store.js
src/situations/accueil/styles/formulaire.scss
src/situations/accueil/vues/formulaire_identification.vue
src/situations/commun/infra/base_registre.js
src/situations/commun/infra/registre_campagne.js
src/situations/commun/infra/registre_utilisateur.js
tests/situations/accueil/modeles/store.js
tests/situations/accueil/vues/formulaire_identification.js
tests/situations/commun/infra/registre_campagne.js
tests/situations/commun/infra/registre_utilisateur.js

pour le ticket https://trello.com/c/PaG7rFkR
Un parametre `horsligne=true` a été ajouté. S'il est absent ou à `false` l'application se comporte comme avant à ceci près que le bénéficaire est prévenu si le réseau n'est pas présent :

Activer le mode offline intentionnellement

---

src/situations/accueil/vues/formulaire_identification.vue
tests/situations/accueil/vues/formulaire_identification.js

Pour : https://trello.com/c/filvWZUX/705-on-ne-veut-plus-forcer-le-code-en-majuscule-c%C3%B4t%C3%A9-client

Force le code campagne en majuscule au focus out

---

package-lock.json
package.json
webpack.config.js

Cette PR est a mergé de préférence après #1032

2/2 Spécifie la version de corejs pour babel

---

src/app/situation_controle.js

Pour : https://trello.com/c/c4Jex09p/807-biscuits-r%C3%A9duire-%C3%A0-2mn

Réduit la cadence à 3s de la situation contrôle

---

src/situations/commun/vues/consigne.vue

Accueil : n'essaye pas de traduire l'aide complementaire puisqu'il n'y en a pas

---

src/situations/accueil/infra/depot_ressources_accueil.js
src/situations/accueil/vues/accueil.vue
src/situations/commun/composants/joueur_audio_buffer.js
src/situations/commun/vues/intro_consigne.vue
tests/situations/commun/composants/joueur_audio_buffer.test.js

#266 Cannot read property stop of undefined/null expression
https://rollbar.com/eva-betagouv/eva/items/266/
#253 TypeError: Erreur vue.js dans la méthode data()
https://rollbar.com/eva-betagouv/eva/items/253/

Fixe 2 erreurs remontées par Rollbar

---

src/situations/accueil/modeles/store.js
src/situations/accueil/styles/deconnexion.scss
src/situations/accueil/styles/fin.scss
src/situations/accueil/vues/bouton_deconnexion.vue
src/situations/accueil/vues/fin.vue
tests/situations/accueil/modeles/store.test.js
tests/situations/accueil/vues/bouton_deconnexion.test.js
tests/situations/accueil/vues/fin.test.js

évalué sans compétences fortes, je peux me déconnecter depuis l'écran des résultats

---

src/situations/accueil/vues/accueil.vue
tests/situations/accueil/vues/accueil.test.js

Restaure l'animation qui se produit au retour à l'accueil

---

package-lock.json
package.json
src/situations/commun/infra/registre_utilisateur.js
tests/situations/commun/infra/registre_utilisateur.test.js

Pour : https://trello.com/c/Z0qHMlBi/756-quand-jarrive-sur-lapp-et-quil-y-a-une-session-en-cours-de-plus-de-4h-%C3%A7a-la-d%C3%A9connecte

Déconnecte une session après 4 h

---

src/locales/fr.json

Pour : https://trello.com/c/LeOTV0e8/818-biscuits-nouvelle-consigne

Modifie la consigne de la situation contrôle

---

src/situations/commun/infra/registre_utilisateur.js
tests/situations/commun/infra/registre_utilisateur.test.js

avec étienne on a fait des trucs cool

Réorganise le fichier de test pour RegistreUtilisateur 

---

src/situations/commun/styles/couleurs.scss
src/situations/commun/styles/formulaire_qcm.scss
src/situations/commun/styles/jauge.scss
src/situations/commun/vues/jauge.vue
src/situations/commun/vues/qcm.vue
tests/situations/commun/vues/jauge.test.js

Pour : https://trello.com/c/BuD7bb9N/606-1-%C3%A0-7-bienvenue-adaptation-pc-tactile

Intégration jauge question choix

---

src/app/index.js

https://stackoverflow.com/questions/3391576/how-can-i-implement-prepend-and-append-with-regular-javascript
https://rollbar.com/eva-betagouv/eva/items/393/

Fix: Corrige une erreur sous Edge. La function prepend n'est pas géré

---

src/situations/commun/styles/jauge.scss

Bienvenue : Ajout d'un espace entre la question et le conteneur jauge

---

src/situations/accueil/styles/fin.scss
src/situations/accueil/vues/fin.vue

Pour : https://trello.com/c/hp7ifRAp/983-mise-en-page-votre-potentiel

Nouvelle mise en page de l'écran votre potentiel

---

src/situations/accueil/styles/fin.scss
tests/situations/accueil/vues/fin.test.js

problèmes de mise en forme sur la page de restitution des compétences et warnings de tests

---

src/situations/commun/styles/pagination.scss
src/situations/commun/vues/components/pagination.vue
src/situations/plan_de_la_ville/vues/plan_de_la_ville.vue
src/situations/questions/modeles/store.js
src/situations/questions/vues/acte.vue
tests/situations/commun/vues/components/pagination.test.js
tests/situations/questions/modeles/store.test.js

Insertion pagination a plan de la ville et refactorisation style scss

---

src/situations/accueil/styles/fin.scss
src/situations/accueil/vues/fin.vue
src/situations/commun/styles/consigne.scss
src/situations/commun/styles/modale.scss
src/situations/commun/vues/consigne.vue

Bug: la barre de déconnexion est décalée quand la description des compétences fortes est très longue

---

src/locales/fr.json
src/situations/questions/infra/depot_ressources_questions.js
tests/situations/questions/infra/depot_resources_questions.test.js

- Un test s'assure qu'on arrive bien à étendre DepotRessourcesCommmune
- ajoute l'aide Calculatrice

Corrige l'affichage de la situation Question (le Bureau)

---

src/public/template_index.html
src/situations/commun/styles/commun.scss
webpack.config.js

Ajoute un numéro de version dans le footer

---

package-lock.json

Pour corriger un problème de sécurité

Mets à jour le package follow-redirects

---

package-lock.json

Resultat de l'execution de npm audit fix

---

src/situations/accueil/infra/depot_ressources_accueil.js
src/situations/bienvenue/infra/depot_ressources_bienvenue.js
src/situations/commun/infra/depot_ressources_communes.js
src/situations/commun/styles/consigne.scss
src/situations/commun/vues/consigne.vue
src/situations/commun/vues/intro_consigne.vue
src/situations/controle/infra/depot_ressources_controle.js
src/situations/inventaire/infra/depot_ressources_inventaire.js
src/situations/livraison/infra/depot_ressources_livraison.js
src/situations/maintenance/infra/depot_ressources_maintenance.js
src/situations/objets_trouves/infra/depot_ressources_objets_trouves.js
src/situations/plan_de_la_ville/infra/depot_ressources_plan_de_la_ville.js
src/situations/prevention/infra/depot_ressources_prevention.js
src/situations/questions/infra/depot_ressources_questions.js
src/situations/securite/infra/depot_ressources_securite.js
src/situations/tri/infra/depot_ressources_tri.js
tests/situations/commun/infra/depot_ressources_communes.test.js
tests/situations/commun/vues/adaptateur_consigne.test.js
tests/situations/commun/vues/intro_consigne.test.js

Affiche une image de fond derrière la consigne quand c'est ça qu'on préfère

---

src/situations/accueil/styles/formulaire.scss
src/situations/accueil/vues/formulaire_identification.vue
src/situations/commun/styles/defi/champ_saisie.scss
src/situations/commun/vues/defi/champ_saisie.vue
tests/situations/accueil/vues/formulaire_identification.test.js
tests/situations/commun/vues/defi/champ_saisie.test.js

Ajout d'un champ de saisie grisé si la campagne est renseignée et valide

---

src/situations/commun/infra/registre_campagne.js
tests/situations/commun/infra/registre_campagne.test.js

https://rollbar.com/eva-betagouv/eva/items/487/

Fix l'erreur rollbar 487

---

src/situations/commun/modeles/store.js
src/situations/commun/vues/defi.vue
src/situations/questions/vues/acte.vue
tests/situations/commun/modeles/store.test.js
tests/situations/commun/vues/defi.test.js

1096 n'envoyer lévénement affichequestionqcm de la première question quaprès avoir cliquer sur commencer

---

src/situations/accueil/modeles/store.js
src/situations/accueil/vues/accueil.vue
src/situations/accueil/vues/fin.vue
tests/situations/accueil/modeles/store.test.js
tests/situations/accueil/vues/accueil.test.js
tests/situations/accueil/vues/fin.test.js

Plutôt que d'attendre l'ouverture du bâtiment résultat

Termine l'évaluation quand on affiche le dernier bâtiment

---

src/situations/cafe_de_la_place/data/defis.js
src/situations/cafe_de_la_place/styles/clic_sur_mots.scss
src/situations/cafe_de_la_place/styles/texte_a_trous.scss
src/situations/cafe_de_la_place/vues/cafe_de_la_place.vue
src/situations/cafe_de_la_place/vues/components/texte_a_trous.vue
src/situations/cafe_de_la_place/vues/components/trou_a_completer.vue
tests/situations/cafe_de_la_place/vues/components/trou_a_completer.test.js

Aplc1 ajout texte a trou

---

src/situations/cafe_de_la_place/modeles/store.js
src/situations/cafe_de_la_place/styles/texte_a_trous.scss
src/situations/cafe_de_la_place/vues/cafe_de_la_place.vue
src/situations/cafe_de_la_place/vues/components/texte_a_trous.vue
src/situations/cafe_de_la_place/vues/components/trou_a_completer.vue
tests/situations/cafe_de_la_place/modeles/store.test.js
tests/situations/cafe_de_la_place/vues/cafe_de_la_place.test.js
tests/situations/cafe_de_la_place/vues/components/trou_a_completer.test.js

A plc2 a a plc20 afficher les saisies

---

src/situations/cafe_de_la_place/data/defis.js
src/situations/cafe_de_la_place/infra/depot_ressources_cafe_de_la_place.js
src/situations/commun/styles/defi.scss
src/situations/commun/styles/defi/champ_saisie.scss
src/situations/commun/vues/defi.vue

A plc retrait modalite de reponse

---

src/situations/cafe_de_la_place/styles/puzzle.scss
src/situations/cafe_de_la_place/vues/components/puzzle.vue
tests/situations/cafe_de_la_place/vues/components/puzzle.test.js

1277 hpar1 3 5 les blocs à droite

---

.circleci/config.yml
package-lock.json
package.json
src/locales/fr.json
src/situations/cafe_de_la_place/styles/puzzle.scss
src/situations/cafe_de_la_place/vues/components/puzzle.vue
tests/situations/cafe_de_la_place/vues/components/puzzle.test.js

Attention, cette PR suppose de mettre à jour la version de node à au moins 16.15

1278 hpar1 4/5 les placeholders

---

src/situations/cafe_de_la_place/data/parcours_haut.js
src/situations/cafe_de_la_place/modeles/store.js
src/situations/cafe_de_la_place/styles/puzzle.scss
src/situations/cafe_de_la_place/vues/components/poignee_puzzle.vue
src/situations/cafe_de_la_place/vues/components/puzzle.vue
tests/situations/cafe_de_la_place/vues/components/puzzle.test.js

Attention, à merger après les placeholders https://github.com/betagouv/eva/pull/1241
* renomme les nouvellesDuJours en fragmentsDuJours
* déplace les fragementsDuJours dans la question HPar1 plutôt que dans la série contenant cette question
* contient aussi la factorisation des poignées des fragments de puzzle.
* utilise les id pour donner l'information de la bonne position (ce qui permet aussi de lire facilement les réponses coté serveur) La bonne réponse c'est donc: [0, 1, 2, 3, 4, 5, 6]

HPar1 superadmin je peux consulter les réponses

---

src/locales/fr.json
src/situations/accueil/vues/index.vue
src/situations/accueil/vues/overlay_erreur_lecture_son.vue
src/situations/commun/styles/action_overlay.scss
src/situations/commun/styles/overlay.scss
tests/situations/accueil/vues/index.test.js

Affiche un message d'erreur si lecture mp3 impossible

---

src/situations/cafe_de_la_place/data/parcours_haut.js
src/situations/cafe_de_la_place/vues/components/graphique.vue
tests/situations/cafe_de_la_place/vues/components/graphique.test.js

HGac envoie des réponses avec score et succes

---

src/situations/cafe_de_la_place/data/parcours_bas.js
src/situations/commun/styles/defi/champ_saisie.scss
src/situations/commun/vues/defi/champ_saisie.vue
src/situations/plan_de_la_ville/data/defis.js

ajout l'autofocus sur le champ de saisie pour le rendre plus visible

---

src/situations/cafe_de_la_place/data/parcours_haut.js

⚠️⚠️ A merger après la PR qui intégre les questions 9 à 20 d'HPfb
https://github.com/betagouv/eva/pull/1278

1343 hpfb évalué je peux avoir un score différent sur certains mots

---

src/situations/plan_de_la_ville/styles/drag_and_drop.scss
src/situations/plan_de_la_ville/vues/components/drag_and_drop.vue
tests/situations/plan_de_la_ville/vues/components/drag_and_drop.test.js

https://www.loom.com/share/4d80715ffafe4f5da530c7b252113b4c

remet l'église à sa place originale lorsqu'on lâche la piece

---

src/situations/plan_de_la_ville/styles/drag_and_drop.scss
src/situations/plan_de_la_ville/vues/components/drag_and_drop.vue
tests/situations/plan_de_la_ville/vues/components/drag_and_drop.test.js

https://www.loom.com/share/8a8ac0108a1241f29cbc3e44835de2a9

Ajoute animation flottante sur l'église du drag & drop de plan de la ville

---

src/situations/accueil/vues/formulaire_identification.vue

renvoie la résolution d'écran disponible au lieu de la résolution d'écran absolue de l'appareil

---

package-lock.json
package.json
src/situations/accueil/vues/formulaire_identification.vue
src/situations/commun/infra/registre_utilisateur.js
tests/situations/accueil/vues/formulaire_identification.test.js

On ne fait plus de parsing du userAgent coté appli

Migration vers l'enregistrement du useragent dans les conditions de passation

---

src/situations/cafe_de_la_place/data/orientation.js
src/situations/cafe_de_la_place/data/parcours_bas.js
src/situations/cafe_de_la_place/data/parcours_haut.js
src/situations/cafe_de_la_place/infra/depot_ressources_cafe_de_la_place.js

Pour corriger "1410 🐛 erreur de son pour la question aplc20"

Force les noms techniques des réponses audio à inclure le répertoire de la ressource

---

src/situations/commun/styles/chargement.scss
src/situations/commun/styles/erreur_chargement.scss

🐛  Remets à taille les 3 petits points ainsi que le bouton de rechargement en cas d'erreur

---

src/situations/cafe_de_la_place/data/parcours_bas.js
src/situations/cafe_de_la_place/data/parcours_haut.js
src/situations/cafe_de_la_place/vues/cafe_de_la_place.vue

Cette PR change aucun comportement. Elle prépare la migration vue 3 en respectant la convention sur le nommage des composants vue.

les extentionsVue doivent être avec des - du 6 (pour la migration v3)

---

package-lock.json
package.json
src/locales/fr.json
src/situations/accueil/modeles/store.js
src/situations/accueil/styles/accueil.scss
src/situations/accueil/styles/formulaire.scss
src/situations/accueil/vues/accueil.vue
src/situations/accueil/vues/champ_formulaire.vue
src/situations/accueil/vues/formulaire_donnees_complementaires.vue
src/situations/accueil/vues/formulaire_identification.vue
src/situations/commun/infra/registre_utilisateur.js
src/situations/commun/styles/champ.scss
src/situations/commun/styles/commun.scss
src/situations/commun/styles/defi/champ_saisie.scss
src/situations/commun/styles/typography.scss
tests/situations/accueil/modeles/store.test.js
tests/situations/accueil/vues/accueil.test.js
tests/situations/accueil/vues/formulaire_donnees_complementaires.test.js
tests/situations/commun/infra/registre_utilisateur.test.js
tests/situations/commun/infra/synchronisateur.test.js

1452 évalué je peux saisir mes données socio démographiques

---

package-lock.json
package.json
src/situations/accueil/vues/champ_formulaire.vue
src/situations/cafe_de_la_place/vues/cafe_de_la_place.vue
src/situations/commun/composants/draggable.js
src/situations/commun/vues/adaptateur_consigne.js
tests/situations/cafe_de_la_place/vues/cafe_de_la_place.test.js
tests/situations/cafe_de_la_place/vues/components/puzzle.test.js
tests/situations/commun/vues/adaptateur_consigne.test.js
webpack.config.js

Cette PR termine la migration vers vue3

Vue 3 sans compatibilité

---

src/app/situation_inventaire.js
src/situations/commun/vues/cadre.js
src/situations/inventaire/data/stock.js
src/situations/inventaire/modeles/situation.js
tests/situations/commun/vues/cadre.test.js

Ajoute le numéro de version de l'inventaire à l'évenement démarrage

---

package-lock.json

En particulier :
- mise à jour de rollbar à la version 2.26.3

Actulisation des dépendances

---

src/app/situation_place_du_marche.js
src/locales/fr.json
src/situations/place_du_marche/data/defis.js
src/situations/place_du_marche/data/numeratie.js
src/situations/place_du_marche/infra/depot_ressources_place_du_marche.js
src/situations/place_du_marche/modeles/store.js
src/situations/place_du_marche/vues/place_du_marche.vue
src/situations/place_du_marche/vues/situation.js
webpack.config.js

Initialise situation place du marché avec questions

---

src/locales/fr.json
src/situations/cafe_de_la_place/data/orientation.js
src/situations/cafe_de_la_place/data/parcours_bas.js
src/situations/cafe_de_la_place/data/parcours_haut.js
src/situations/commun/vues/defi.vue
src/situations/commun/vues/question_entete.vue
src/situations/objets_trouves/data/apps.js
tests/situations/commun/vues/defi.test.js
tests/situations/commun/vues/question_entete.test.js

On envoie au back-office l'ensemble des informations pour savoir l'intitulé de la question et le score max.
Les textes des intitulés proviennent du document "Textes des Mises en situation"
https://captive-team.atlassian.net/browse/EVA-45

EVA 45 Le conseiller peut consulter le détail de la question dans l'export détaillé

---

src/situations/cafe_de_la_place/data/orientation.js
src/situations/cafe_de_la_place/data/parcours_bas.js
src/situations/commun/vues/defi.vue
tests/situations/commun/vues/defi.test.js

afin qu'elle ne soit pas affichés dans le jeu

🐛 Change "intitule" par "retranscription_audio" pour les réponses

---

src/situations/place_du_marche/data/defis.js
src/situations/place_du_marche/data/numeratie.js
src/situations/place_du_marche/data/rattrapage.js
src/situations/place_du_marche/modeles/store.js
tests/situations/place_du_marche/modeles/store.test.js

Pour pouvoir tester :
- bonnes réponses Niveau 1
- bonne réponse Niveau 2
- bonne réponse Niveau 3
-> la situation se termine
- bonnes réponses Niveau 1
- mauvaise réponse Niveau 2
-> la situation se termine
- au moins 2 mauvaises réponses Niveau 1 dont 2 bonnes réponses pour les questions Reconnaître les nombres
-> la situation se termine
- au moins 2 mauvaises réponses Niveau 1 dont 1 mauvaise réponse parmi les questions Reconnaître les nombres
-> passage des deux questions du rattrapage
-> la situation se termine

Implémente le rattrapage d'une compétence

---

docs/tech-dive-in/EVA-175-le-joueur-utilise-automatiquement-le-parametrage-de-sa-question-saisie-de-nombre-numeratie/readme.md
src/situations/commun/infra/depot_ressources.js
src/situations/place_du_marche/data/numeratie.js
src/situations/place_du_marche/data/rattrapage.js
src/situations/place_du_marche/modeles/store.js
tests/situations/place_du_marche/modeles/store.test.js

le-joueur-utilise-automatiquement-le-parametrage-de-sa-question-saisie-de-nombre-numeratie

---

docs/tech-dive-in/EVA-181-le-joueur-utilise-automatiquement-le-parametrage-de-sa-question-clic-dans-image/readme.md
src/situations/commun/styles/clic_dans_image.scss
src/situations/commun/vues/components/clic_dans_image.vue
src/situations/commun/vues/defi.vue
src/situations/place_du_marche/data/numeratie.js
src/situations/place_du_marche/infra/depot_ressources_place_du_marche.js
src/situations/place_du_marche/modeles/store.js
tests/situations/commun/vues/components/clic_dans_image.test.js
tests/situations/place_du_marche/infra/depot_ressource_place_du_marche.test.js
tests/situations/place_du_marche/modeles/store.test.js

https://github.com/user-attachments/assets/5109a7bb-0cab-4336-a14f-6e0a5847d3c3

Le joueur utilise automatiquement le paramétrage de sa question Clic dans image

---

src/locales/fr.json
src/situations/cafe_de_la_place/styles/puzzle_journal.scss
src/situations/cafe_de_la_place/vues/components/puzzle_journal.vue
src/situations/commun/styles/glisser_deposer.scss
src/situations/commun/vues/components/glisser_deposer.vue
src/situations/place_du_marche/styles/glisser_deposer_billets.scss
src/situations/place_du_marche/vues/components/glisser_deposer_billets.vue
tests/situations/cafe_de_la_place/vues/components/puzzle_journal.test.js
tests/situations/commun/vues/components/glisser_deposer.test.js

Design validé ici https://captive.slack.com/archives/C02JM8SB5T3/p1726583197097459
Je n'ai pas eu le courage de refaire la vidéo mais le rectangle du bas a le même arrondi que celui du haut.
https://github.com/user-attachments/assets/12fbf3e4-1428-4634-a871-949f6c968af1

Reprise du CSS pour les questions glisser déposer de la numératie

---

docs/tech-dive-in/EVA-199-ladministrateur-peut-fournir-une-image-repere-pour-les-clic-dans-image/readme.md
src/situations/commun/styles/clic_dans_image.scss
src/situations/commun/vues/components/clic_dans_image.vue
tests/situations/commun/vues/components/clic_dans_image.test.js

https://github.com/user-attachments/assets/4ba5ea9d-3928-45a8-a505-067920a44d9c

✨ Place un curseur au clic dans image

---

src/situations/commun/vues/components/glisser_deposer.vue
tests/situations/commun/vues/components/glisser_deposer.test.js

🐛 Extrait le nom technique d'un élement réponse en entier

---

src/situations/commun/styles/champ.scss
src/situations/commun/vues/defi/champ_saisie.vue
tests/situations/commun/vues/defi/champ_saisie.test.js

J'ai quand même laissé une limite pour éviter de casser le design

💄 Recupère la max_lenth, le suffixe réponse et le placeholder du serveur pour une question saisie prix avec centimes

---

src/situations/commun/styles/champ.scss
src/situations/commun/vues/defi/champ_saisie.vue
tests/situations/commun/vues/defi/champ_saisie.test.js

🚚 Renomme le type de saisie prix avec centimes en nombre avec virgule

---

src/situations/commun/vues/rejoue_consigne.js

Afin que le libele "repeter_consigne" ne change pas

💄 Ajoute un libelle au bouton de mise en pause

---

src/situations/commun/styles/defi.scss

La div avec la classe question n'était pas affiché car elle n'était plus en position absolute

🐛 la question puzzle de littératie est cassé

---

src/locales/fr.json
src/situations/cafe_de_la_place/styles/clic_sur_mots.scss
src/situations/commun/styles/defi.scss
src/situations/commun/styles/glisser_deposer.scss
src/situations/commun/vues/components/glisser_deposer.vue
src/situations/commun/vues/components/glisser_deposer_ombre.vue
src/situations/commun/vues/question.vue
src/situations/place_du_marche/styles/glisser_deposer.scss
tests/situations/commun/vues/components/glisser_deposer.test.js

https://captive-team.atlassian.net/browse/EVA-322
https://github.com/user-attachments/assets/ab9df095-b72c-4fbd-8e80-9605c5d9c4a4

Correction puzzle

---

src/situations/commun/vues/components/glisser_deposer.vue
tests/situations/commun/vues/components/glisser_deposer.test.js

Jusqu'alors, si tu envoyés le début de la bonne réponse, alors on renvoyé un succès
https://captive-team.atlassian.net/browse/EVA-347

🐛 Retourne succes: true seulement si tous les éléments sont placées pour le tri

---

src/situations/commun/styles/glisser_deposer.scss
src/situations/place_du_marche/styles/glisser_deposer.scss

https://github.com/user-attachments/assets/32e97e78-9388-46a8-a989-85c554573798

🐛 Corrige le retour à ligne du placeholder dans la tri

---

src/situations/commun/styles/mixins/boutons.scss

Pour éviter d'avoir un changement trop brutal

💄 Ajoute sur un effet de transition sur le hover des boutons

---

src/situations/commun/modeles/store.js
src/situations/commun/vues/bouton_lecture.vue
src/situations/commun/vues/question_entete.vue
tests/situations/commun/modeles/store.test.js
tests/situations/commun/vues/bouton-lecture.test.js

https://captive-team.atlassian.net/browse/EVA-267

EVA-267 - ✨ Le joueur ne doit entendre qu'un audio à la fois 

---

src/situations/commun/styles/clic_dans_image.scss
src/situations/commun/vues/components/clic_dans_image.vue

En cherchant à comprendre l'erreur rollbar https://app.rollbar.com/a/eva-betagouv/fix/item/eva/1217 je me suis retrouvé à refactorer ce code.
Je n'ai pas trouvé le problème de l'erreur par contre.

♻️ Elimine la coincidence pour la taille du curseur de clic_dans_image

---

src/locales/fr.json
src/public/template_index.html
src/situations/accueil/vues/fin.vue
webpack.config.js

* Mise en variable système de cette URL
* Actualisation du domaine dans l'encart d'acceptation des CGU sur la page de connexion

👽️ Migration de l'url des compétences transversales

---

src/locales/fr.json
src/situations/accueil/modeles/store.js
src/situations/accueil/vues/accueil.vue
src/situations/accueil/vues/formulaire_identification.vue
src/situations/accueil/vues/index.vue
src/situations/commun/infra/erreur_connexion_code_personnel.js
src/situations/commun/infra/registre_utilisateur.js
tests/situations/accueil/modeles/store.test.js
tests/situations/accueil/vues/accueil.test.js
tests/situations/accueil/vues/formulaire_identification.test.js
tests/situations/commun/infra/registre_utilisateur.test.js

🔥 Renomme le code personnel en code bénéficiaire
